// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const ensureStatements = `-- name: EnsureStatements :batchone
WITH params AS (
    SELECT
        $1::text   AS server_name,
        $2::text AS database_name,
        $3::text     AS user_name,
        $4::bigint    AS query_id
),
existing AS (
    SELECT s.id
    FROM statements s
    JOIN params p ON s.server_name   = p.server_name
                 AND s.database_name = p.database_name
                 AND s.user_name     = p.user_name
                 AND s.query_id      = p.query_id
),
inserted AS (
    INSERT INTO statements (server_name, database_name, user_name, query_id, query_full, query_short, query_kind)
    SELECT server_name, database_name, user_name, query_id, '', '', 0
    FROM params
    WHERE NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (server_name, database_name, user_name, query_id)
    DO UPDATE SET query_full = statements.query_full
    RETURNING id
)
SELECT id FROM existing
UNION ALL
SELECT id FROM inserted
`

type EnsureStatementsBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type EnsureStatementsParams struct {
	ServerName   string
	DatabaseName string
	UserName     string
	QueryID      int64
}

func (q *Queries) EnsureStatements(ctx context.Context, arg []EnsureStatementsParams) *EnsureStatementsBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.DatabaseName,
			a.UserName,
			a.QueryID,
		}
		batch.Queue(ensureStatements, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &EnsureStatementsBatchResults{br, len(arg), false}
}

func (b *EnsureStatementsBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *EnsureStatementsBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const fillStatementText = `-- name: FillStatementText :batchexec
UPDATE statements
SET query_full = $1,
    query_short = $2,
    query_kind = $3
WHERE server_name = $4
  AND database_name = $5
  AND user_name = $6
  AND query_id = $7
  AND query_full = ''
`

type FillStatementTextBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type FillStatementTextParams struct {
	QueryFull    string
	QueryShort   string
	QueryKind    int32
	ServerName   string
	DatabaseName string
	UserName     string
	QueryID      int64
}

func (q *Queries) FillStatementText(ctx context.Context, arg []FillStatementTextParams) *FillStatementTextBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.QueryFull,
			a.QueryShort,
			a.QueryKind,
			a.ServerName,
			a.DatabaseName,
			a.UserName,
			a.QueryID,
		}
		batch.Queue(fillStatementText, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &FillStatementTextBatchResults{br, len(arg), false}
}

func (b *FillStatementTextBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *FillStatementTextBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertStatementSamples = `-- name: InsertStatementSamples :batchone
INSERT INTO statement_samples (
    server_name, collected_at, occurred_at, statement_id, query,
    duration_ms, parameters, explain_plan_json, tags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id
`

type InsertStatementSamplesBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertStatementSamplesParams struct {
	ServerName      string
	CollectedAt     pgtype.Timestamptz
	OccurredAt      pgtype.Timestamptz
	StatementID     pgtype.Int8
	Query           string
	DurationMs      float64
	Parameters      []string
	ExplainPlanJson pgtype.Text
	Tags            []byte
}

func (q *Queries) InsertStatementSamples(ctx context.Context, arg []InsertStatementSamplesParams) *InsertStatementSamplesBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.CollectedAt,
			a.OccurredAt,
			a.StatementID,
			a.Query,
			a.DurationMs,
			a.Parameters,
			a.ExplainPlanJson,
			a.Tags,
		}
		batch.Queue(insertStatementSamples, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertStatementSamplesBatchResults{br, len(arg), false}
}

func (b *InsertStatementSamplesBatchResults) QueryRow(f func(int, int64, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id int64
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *InsertStatementSamplesBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const recordTransactionEvent = `-- name: RecordTransactionEvent :batchexec
WITH params AS (
    SELECT
        $1::text            AS server_name,
        $2::int                     AS pid,
        $3::timestamptz   AS backend_start,
        $4::timestamptz      AS xact_start,
        $5::text          AS database_name,
        $6::text              AS user_name,
        $7::text       AS application_name,
        $8::timestamptz    AS collected_at,
        $9::text                  AS state,
        $10::text        AS wait_event_type,
        $11::text             AS wait_event,
        $12::timestamptz     AS query_start,
        $13::text                  AS query,
        $14::jsonb            AS query_tags,
        $15::int          AS blocked_by_pid,
        $16::timestamptz AS lock_wait_start,
        $17::text              AS lock_mode
),
norm AS (
    SELECT
        NULLIF(wait_event_type, '') AS wait_event_type,
        NULLIF(wait_event, '')      AS wait_event,
        NULLIF(query, '')           AS query,
        NULLIF(lock_mode, '')       AS lock_mode,
        NULLIF(blocked_by_pid, 0)   AS blocked_by_pid
    FROM params
),
tx AS (
    INSERT INTO transactions (
        server_name, pid, backend_start, xact_start,
        database_name, user_name, application_name, last_seen_at
    )
    SELECT
        server_name, pid, backend_start, xact_start,
        database_name, user_name, application_name, collected_at
    FROM params
    ON CONFLICT (server_name, pid, backend_start, xact_start)
    DO UPDATE SET last_seen_at = GREATEST(transactions.last_seen_at, EXCLUDED.last_seen_at)
    RETURNING id
),
latest AS (
    SELECT e.id, e.state, e.wait_event_type, e.wait_event, e.transaction_query_id, q.query_start,
           e.blocked_by_pid, e.lock_wait_start, e.lock_mode
    FROM transaction_events e
    JOIN transaction_queries q ON q.id = e.transaction_query_id
    JOIN tx ON q.transaction_id = tx.id
    ORDER BY e.first_seen_at DESC, e.id DESC
    LIMIT 1
),
tq_ins AS (
    INSERT INTO transaction_queries (transaction_id, xact_start, query_start, query, query_tags)
    SELECT tx.id, params.xact_start, params.query_start, norm.query, params.query_tags
    FROM tx, norm, params
    WHERE params.query_start IS DISTINCT FROM (SELECT query_start FROM latest)
    ON CONFLICT (transaction_id, query_start, xact_start) DO NOTHING
    RETURNING id
),
tq AS (
    SELECT coalesce(
        (SELECT id FROM tq_ins),
        (SELECT q.id FROM transaction_queries q JOIN tx ON q.transaction_id = tx.id
         WHERE q.query_start IS NOT DISTINCT FROM params.query_start)
    ) AS id
    FROM params
),
extended AS (
    UPDATE transaction_events e
    SET last_seen_at = GREATEST(e.last_seen_at, params.collected_at)
    FROM latest, norm, tq, params
    WHERE e.id = latest.id
      AND latest.transaction_query_id IS NOT DISTINCT FROM tq.id
      AND latest.state           IS NOT DISTINCT FROM params.state
      AND latest.wait_event_type IS NOT DISTINCT FROM norm.wait_event_type
      AND latest.wait_event      IS NOT DISTINCT FROM norm.wait_event
      AND latest.blocked_by_pid  IS NOT DISTINCT FROM norm.blocked_by_pid
      AND latest.lock_wait_start IS NOT DISTINCT FROM params.lock_wait_start
      AND latest.lock_mode       IS NOT DISTINCT FROM norm.lock_mode
    RETURNING e.id
)
INSERT INTO transaction_events (
    transaction_query_id, xact_start, state, wait_event_type, wait_event,
    blocked_by_pid, lock_wait_start, lock_mode, first_seen_at, last_seen_at
)
SELECT tq.id, params.xact_start, params.state, norm.wait_event_type, norm.wait_event,
       norm.blocked_by_pid, params.lock_wait_start, norm.lock_mode, params.collected_at, params.collected_at
FROM tq, norm, params
WHERE NOT EXISTS (SELECT 1 FROM extended)
`

type RecordTransactionEventBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type RecordTransactionEventParams struct {
	ServerName      string
	Pid             int32
	BackendStart    pgtype.Timestamptz
	XactStart       pgtype.Timestamptz
	DatabaseName    string
	UserName        string
	ApplicationName string
	CollectedAt     pgtype.Timestamptz
	State           string
	WaitEventType   string
	WaitEvent       string
	QueryStart      pgtype.Timestamptz
	Query           string
	QueryTags       []byte
	BlockedByPid    int32
	LockWaitStart   pgtype.Timestamptz
	LockMode        string
}

func (q *Queries) RecordTransactionEvent(ctx context.Context, arg []RecordTransactionEventParams) *RecordTransactionEventBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.Pid,
			a.BackendStart,
			a.XactStart,
			a.DatabaseName,
			a.UserName,
			a.ApplicationName,
			a.CollectedAt,
			a.State,
			a.WaitEventType,
			a.WaitEvent,
			a.QueryStart,
			a.Query,
			a.QueryTags,
			a.BlockedByPid,
			a.LockWaitStart,
			a.LockMode,
		}
		batch.Queue(recordTransactionEvent, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RecordTransactionEventBatchResults{br, len(arg), false}
}

func (b *RecordTransactionEventBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RecordTransactionEventBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertAlertToggle = `-- name: UpsertAlertToggle :batchexec
INSERT INTO alert_toggles (server_name, alert_key, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (server_name, alert_key) DO UPDATE SET enabled = EXCLUDED.enabled
`

type UpsertAlertToggleBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertAlertToggleParams struct {
	ServerName string
	AlertKey   string
	Enabled    bool
}

func (q *Queries) UpsertAlertToggle(ctx context.Context, arg []UpsertAlertToggleParams) *UpsertAlertToggleBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ServerName,
			a.AlertKey,
			a.Enabled,
		}
		batch.Queue(upsertAlertToggle, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertAlertToggleBatchResults{br, len(arg), false}
}

func (b *UpsertAlertToggleBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertAlertToggleBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
