// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForInsertLogEvents implements pgx.CopyFromSource.
type iteratorForInsertLogEvents struct {
	rows                 []InsertLogEventsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertLogEvents) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertLogEvents) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ServerName,
		r.rows[0].CollectedAt,
		r.rows[0].OccurredAt,
		r.rows[0].LogLevel,
		r.rows[0].Classification,
		r.rows[0].Message,
		r.rows[0].Pid,
		r.rows[0].Username,
		r.rows[0].DatabaseName,
		r.rows[0].ApplicationName,
		r.rows[0].Detail,
		r.rows[0].Hint,
		r.rows[0].Context,
		r.rows[0].Statement,
		r.rows[0].BackendType,
		r.rows[0].StateCode,
		r.rows[0].StatementSampleID,
	}, nil
}

func (r iteratorForInsertLogEvents) Err() error {
	return nil
}

func (q *Queries) InsertLogEvents(ctx context.Context, arg []InsertLogEventsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"log_events"}, []string{"server_name", "collected_at", "occurred_at", "log_level", "classification", "message", "pid", "username", "database_name", "application_name", "detail", "hint", "context", "statement", "backend_type", "state_code", "statement_sample_id"}, &iteratorForInsertLogEvents{rows: arg})
}

// iteratorForInsertStatementDeltas implements pgx.CopyFromSource.
type iteratorForInsertStatementDeltas struct {
	rows                 []InsertStatementDeltasParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStatementDeltas) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStatementDeltas) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StatementID,
		r.rows[0].CollectedAt,
		r.rows[0].Calls,
		r.rows[0].Rows,
		r.rows[0].TotalExecTime,
		r.rows[0].TotalIoTime,
	}, nil
}

func (r iteratorForInsertStatementDeltas) Err() error {
	return nil
}

func (q *Queries) InsertStatementDeltas(ctx context.Context, arg []InsertStatementDeltasParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"statement_deltas"}, []string{"statement_id", "collected_at", "calls", "rows", "total_exec_time", "total_io_time"}, &iteratorForInsertStatementDeltas{rows: arg})
}
