// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertNotification struct {
	ServerName  string
	AlertKey    string
	LastFiredAt pgtype.Timestamptz
}

type AlertSetting struct {
	ServerName      string
	SlackWebhookUrl string
}

type AlertToggle struct {
	ServerName string
	AlertKey   string
	Enabled    bool
}

type CollectorHealth struct {
	ServerName  string
	CollectedAt pgtype.Timestamptz
	Databases   []string
}

type CollectorToken struct {
	ID         int64
	ServerName string
	TokenHash  string
	CreatedAt  pgtype.Timestamptz
}

type LogEvent struct {
	ID                int64
	CollectedAt       pgtype.Timestamptz
	ServerName        string
	OccurredAt        pgtype.Timestamptz
	LogLevel          int32
	Classification    int32
	Message           pgtype.Text
	Pid               pgtype.Int4
	Username          pgtype.Text
	DatabaseName      pgtype.Text
	ApplicationName   pgtype.Text
	Detail            pgtype.Text
	Hint              pgtype.Text
	Context           pgtype.Text
	Statement         pgtype.Text
	BackendType       pgtype.Text
	StateCode         pgtype.Text
	StatementSampleID pgtype.Int8
}

type LogEventsDefault struct {
	ID              int64
	CollectedAt     pgtype.Timestamptz
	ServerName      string
	OccurredAt      pgtype.Timestamptz
	LogLevel        int32
	Classification  int32
	Message         pgtype.Text
	Pid             pgtype.Int4
	Username        pgtype.Text
	DatabaseName    pgtype.Text
	ApplicationName pgtype.Text
	Detail          pgtype.Text
	Hint            pgtype.Text
	Context         pgtype.Text
	Statement       pgtype.Text
	BackendType     pgtype.Text
	StateCode       pgtype.Text
}

type Statement struct {
	ID           int64
	ServerName   string
	DatabaseName string
	UserName     string
	QueryID      int64
	QueryFull    string
	QueryShort   string
	QueryKind    int32
}

type StatementDelta struct {
	ID            int64
	CollectedAt   pgtype.Timestamptz
	StatementID   int64
	Calls         int64
	Rows          int64
	TotalExecTime float64
	TotalIoTime   float64
}

type StatementDeltasDefault struct {
	ID            int64
	CollectedAt   pgtype.Timestamptz
	StatementID   int64
	Calls         int64
	Rows          int64
	TotalExecTime float64
	TotalIoTime   float64
}

type StatementSample struct {
	ID              int64
	CollectedAt     pgtype.Timestamptz
	ServerName      string
	OccurredAt      pgtype.Timestamptz
	StatementID     pgtype.Int8
	Query           string
	DurationMs      float64
	Parameters      []string
	ExplainPlanJson pgtype.Text
	Tags            []byte
}

type StatementSamplesDefault struct {
	ID              int64
	CollectedAt     pgtype.Timestamptz
	ServerName      string
	OccurredAt      pgtype.Timestamptz
	LogEventID      pgtype.Int8
	StatementID     pgtype.Int8
	Query           string
	DurationMs      float64
	Parameters      []string
	ExplainPlanJson pgtype.Text
	Tags            []byte
}

type Transaction struct {
	ID              int64
	XactStart       pgtype.Timestamptz
	ServerName      string
	Pid             int32
	BackendStart    pgtype.Timestamptz
	DatabaseName    string
	UserName        string
	ApplicationName string
	LastSeenAt      pgtype.Timestamptz
}

type TransactionEvent struct {
	ID                 int64
	XactStart          pgtype.Timestamptz
	TransactionQueryID int64
	State              string
	WaitEventType      pgtype.Text
	WaitEvent          pgtype.Text
	BlockedByPid       pgtype.Int4
	LockWaitStart      pgtype.Timestamptz
	LockMode           pgtype.Text
	FirstSeenAt        pgtype.Timestamptz
	LastSeenAt         pgtype.Timestamptz
}

type TransactionEventsDefault struct {
	ID                 int64
	XactStart          pgtype.Timestamptz
	TransactionQueryID int64
	State              string
	WaitEventType      pgtype.Text
	WaitEvent          pgtype.Text
	BlockedByPid       pgtype.Int4
	LockWaitStart      pgtype.Timestamptz
	LockMode           pgtype.Text
	FirstSeenAt        pgtype.Timestamptz
	LastSeenAt         pgtype.Timestamptz
}

type TransactionQueriesDefault struct {
	ID            int64
	XactStart     pgtype.Timestamptz
	TransactionID int64
	QueryStart    pgtype.Timestamptz
	Query         string
	QueryTags     []byte
}

type TransactionQuery struct {
	ID            int64
	XactStart     pgtype.Timestamptz
	TransactionID int64
	QueryStart    pgtype.Timestamptz
	Query         string
	QueryTags     []byte
}

type TransactionsDefault struct {
	ID              int64
	XactStart       pgtype.Timestamptz
	ServerName      string
	Pid             int32
	BackendStart    pgtype.Timestamptz
	DatabaseName    string
	UserName        string
	ApplicationName string
	LastSeenAt      pgtype.Timestamptz
}

type User struct {
	ID             int64
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	AllowedServers []string
	CreatedAt      pgtype.Timestamptz
}

type UserSession struct {
	TokenHash string
	UserID    int64
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}
