// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCollectorTokensForServer = `-- name: CountCollectorTokensForServer :one
SELECT count(*) AS total FROM collector_tokens WHERE server_name = $1
`

func (q *Queries) CountCollectorTokensForServer(ctx context.Context, serverName string) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectorTokensForServer, serverName)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countRecentAlertFires = `-- name: CountRecentAlertFires :many
SELECT server_name, alert_key, count(*) AS fires
FROM alert_fires
WHERE fired_at >= now() - $1::interval
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
GROUP BY server_name, alert_key
`

type CountRecentAlertFiresParams struct {
	HistoryWindow  pgtype.Interval
	AllowedServers []string
}

type CountRecentAlertFiresRow struct {
	ServerName string
	AlertKey   string
	Fires      int64
}

func (q *Queries) CountRecentAlertFires(ctx context.Context, arg CountRecentAlertFiresParams) ([]CountRecentAlertFiresRow, error) {
	rows, err := q.db.Query(ctx, countRecentAlertFires, arg.HistoryWindow, arg.AllowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRecentAlertFiresRow
	for rows.Next() {
		var i CountRecentAlertFiresRow
		if err := rows.Scan(&i.ServerName, &i.AlertKey, &i.Fires); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) AS total FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCollectorToken = `-- name: CreateCollectorToken :one
INSERT INTO collector_tokens (server_name, token_hash)
VALUES ($1, $2)
RETURNING id, server_name, created_at
`

type CreateCollectorTokenParams struct {
	ServerName string
	TokenHash  string
}

type CreateCollectorTokenRow struct {
	ID         int64
	ServerName string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateCollectorToken(ctx context.Context, arg CreateCollectorTokenParams) (CreateCollectorTokenRow, error) {
	row := q.db.QueryRow(ctx, createCollectorToken, arg.ServerName, arg.TokenHash)
	var i CreateCollectorTokenRow
	err := row.Scan(&i.ID, &i.ServerName, &i.CreatedAt)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, is_super_admin, allowed_servers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, is_super_admin, created_at, allowed_servers
`

type CreateUserParams struct {
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	AllowedServers []string
}

type CreateUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsSuperAdmin,
		arg.AllowedServers,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const deleteAlertConfigForServer = `-- name: DeleteAlertConfigForServer :exec
WITH cleared_settings AS (
    DELETE FROM alert_settings WHERE alert_settings.server_name = $1
),
cleared_toggles AS (
    DELETE FROM alert_toggles WHERE alert_toggles.server_name = $1
),
cleared_fires AS (
    DELETE FROM alert_fires WHERE alert_fires.server_name = $1
)
DELETE FROM alert_notifications WHERE alert_notifications.server_name = $1
`

func (q *Queries) DeleteAlertConfigForServer(ctx context.Context, serverName string) error {
	_, err := q.db.Exec(ctx, deleteAlertConfigForServer, serverName)
	return err
}

const deleteCollectorToken = `-- name: DeleteCollectorToken :one
DELETE FROM collector_tokens WHERE id = $1
RETURNING server_name
`

func (q *Queries) DeleteCollectorToken(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, deleteCollectorToken, id)
	var server_name string
	err := row.Scan(&server_name)
	return server_name, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const filterStatementIDsByTags = `-- name: FilterStatementIDsByTags :many
WITH scoped AS (
    SELECT s.id
    FROM statements s
    WHERE ($2::text IS NULL OR s.server_name = $2)
      AND ($3::text IS NULL OR s.database_name = $3)
      AND ($4::text[] IS NULL OR s.server_name = ANY($4::text[]))
),
agreed AS (
    SELECT ss.statement_id, kv.key, min(kv.value) AS value
    FROM statement_samples ss
    JOIN scoped ON scoped.id = ss.statement_id
    CROSS JOIN LATERAL jsonb_each_text(ss.tags) AS kv(key, value)
    WHERE ss.tags IS NOT NULL
      AND kv.key NOT LIKE '%\_id'
      AND ss.collected_at >= $5::timestamptz
      AND ss.collected_at <= $6::timestamptz
      AND kv.key IN (SELECT f ->> 'key' FROM jsonb_array_elements($1::jsonb) AS f)
    GROUP BY ss.statement_id, kv.key
    HAVING count(DISTINCT kv.value) = 1
)
SELECT scoped.id
FROM scoped
WHERE NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements($1::jsonb) AS f
    WHERE NOT CASE f ->> 'op'
        WHEN 'ne' THEN NOT EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
              AND a.value IN (SELECT jsonb_array_elements_text(f -> 'values'))
        )
        WHEN 'exists' THEN EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
        )
        ELSE EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
              AND a.value IN (SELECT jsonb_array_elements_text(f -> 'values'))
        )
    END
)
`

type FilterStatementIDsByTagsParams struct {
	TagFilters     []byte
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
}

func (q *Queries) FilterStatementIDsByTags(ctx context.Context, arg FilterStatementIDsByTagsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, filterStatementIDsByTags,
		arg.TagFilters,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertEnabled = `-- name: GetAlertEnabled :one
SELECT enabled FROM alert_toggles WHERE server_name = $1 AND alert_key = $2
`

type GetAlertEnabledParams struct {
	ServerName string
	AlertKey   string
}

func (q *Queries) GetAlertEnabled(ctx context.Context, arg GetAlertEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, getAlertEnabled, arg.ServerName, arg.AlertKey)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getAlertWebhook = `-- name: GetAlertWebhook :one
SELECT slack_webhook_url FROM alert_settings WHERE server_name = $1
`

func (q *Queries) GetAlertWebhook(ctx context.Context, serverName string) (string, error) {
	row := q.db.QueryRow(ctx, getAlertWebhook, serverName)
	var slack_webhook_url string
	err := row.Scan(&slack_webhook_url)
	return slack_webhook_url, err
}

const getCollectorServerByHash = `-- name: GetCollectorServerByHash :one
SELECT server_name FROM collector_tokens WHERE token_hash = $1
`

func (q *Queries) GetCollectorServerByHash(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getCollectorServerByHash, tokenHash)
	var server_name string
	err := row.Scan(&server_name)
	return server_name, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.name, u.email, u.is_super_admin, u.created_at, u.allowed_servers
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const getStatementDetail = `-- name: GetStatementDetail :one
SELECT
    s.query_full AS query,
    s.server_name,
    s.database_name,
    coalesce(st.tags, '{}'::jsonb) AS tags
FROM statements s
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(per_key.key, per_key.value) AS tags
    FROM (
        SELECT
            kv.key,
            min(kv.value) AS value
        FROM statement_samples qs
        CROSS JOIN LATERAL jsonb_each_text(qs.tags) AS kv(key, value)
        WHERE qs.statement_id = s.id
          AND qs.tags IS NOT NULL
          AND kv.key NOT LIKE '%\_id'
          AND ($1::timestamptz IS NULL OR qs.collected_at >= $1)
          AND ($2::timestamptz IS NULL OR qs.collected_at <= $2)
        GROUP BY kv.key
        HAVING count(DISTINCT kv.value) = 1
    ) per_key
) st ON true
WHERE s.id = $3
  AND ($4::text[] IS NULL OR s.server_name = ANY($4::text[]))
`

type GetStatementDetailParams struct {
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	StatementID    int64
	AllowedServers []string
}

type GetStatementDetailRow struct {
	Query        string
	ServerName   string
	DatabaseName string
	Tags         []byte
}

func (q *Queries) GetStatementDetail(ctx context.Context, arg GetStatementDetailParams) (GetStatementDetailRow, error) {
	row := q.db.QueryRow(ctx, getStatementDetail,
		arg.Since,
		arg.Until,
		arg.StatementID,
		arg.AllowedServers,
	)
	var i GetStatementDetailRow
	err := row.Scan(
		&i.Query,
		&i.ServerName,
		&i.DatabaseName,
		&i.Tags,
	)
	return i, err
}

const getStatementSamplePlan = `-- name: GetStatementSamplePlan :one
SELECT query, parameters, explain_plan_json
FROM statement_samples
WHERE id = $1
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
`

type GetStatementSamplePlanParams struct {
	SampleID       int64
	AllowedServers []string
}

type GetStatementSamplePlanRow struct {
	Query           string
	Parameters      []string
	ExplainPlanJson pgtype.Text
}

func (q *Queries) GetStatementSamplePlan(ctx context.Context, arg GetStatementSamplePlanParams) (GetStatementSamplePlanRow, error) {
	row := q.db.QueryRow(ctx, getStatementSamplePlan, arg.SampleID, arg.AllowedServers)
	var i GetStatementSamplePlanRow
	err := row.Scan(&i.Query, &i.Parameters, &i.ExplainPlanJson)
	return i, err
}

const getStatementSampleText = `-- name: GetStatementSampleText :one
SELECT query, parameters
FROM statement_samples
WHERE id = $1
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
`

type GetStatementSampleTextParams struct {
	SampleID       int64
	AllowedServers []string
}

type GetStatementSampleTextRow struct {
	Query      string
	Parameters []string
}

func (q *Queries) GetStatementSampleText(ctx context.Context, arg GetStatementSampleTextParams) (GetStatementSampleTextRow, error) {
	row := q.db.QueryRow(ctx, getStatementSampleText, arg.SampleID, arg.AllowedServers)
	var i GetStatementSampleTextRow
	err := row.Scan(&i.Query, &i.Parameters)
	return i, err
}

const getStatementText = `-- name: GetStatementText :one
SELECT query_full
FROM statements
WHERE id = $1
  AND ($2::text[] IS NULL
       OR server_name = ANY($2::text[]))
`

type GetStatementTextParams struct {
	ID             int64
	AllowedServers []string
}

func (q *Queries) GetStatementText(ctx context.Context, arg GetStatementTextParams) (string, error) {
	row := q.db.QueryRow(ctx, getStatementText, arg.ID, arg.AllowedServers)
	var query_full string
	err := row.Scan(&query_full)
	return query_full, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, is_super_admin, created_at, allowed_servers
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, is_super_admin, created_at, allowed_servers
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int64
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

type InsertLogEventsParams struct {
	ServerName        string
	CollectedAt       pgtype.Timestamptz
	OccurredAt        pgtype.Timestamptz
	LogLevel          int32
	Classification    int32
	Message           pgtype.Text
	Pid               pgtype.Int4
	Username          pgtype.Text
	DatabaseName      pgtype.Text
	ApplicationName   pgtype.Text
	Detail            pgtype.Text
	Hint              pgtype.Text
	Context           pgtype.Text
	Statement         pgtype.Text
	BackendType       pgtype.Text
	StateCode         pgtype.Text
	StatementSampleID pgtype.Int8
}

type InsertStatementDeltasParams struct {
	StatementID   int64
	CollectedAt   pgtype.Timestamptz
	Calls         int64
	Rows          int64
	TotalExecTime float64
	TotalIoTime   float64
}

const listAlertToggles = `-- name: ListAlertToggles :many
SELECT server_name, alert_key, enabled
FROM alert_toggles
WHERE ($1::text[] IS NULL OR server_name = ANY($1::text[]))
`

func (q *Queries) ListAlertToggles(ctx context.Context, allowedServers []string) ([]AlertToggle, error) {
	rows, err := q.db.Query(ctx, listAlertToggles, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertToggle
	for rows.Next() {
		var i AlertToggle
		if err := rows.Scan(&i.ServerName, &i.AlertKey, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertWebhooks = `-- name: ListAlertWebhooks :many
SELECT server_name, slack_webhook_url
FROM alert_settings
WHERE ($1::text[] IS NULL OR server_name = ANY($1::text[]))
`

func (q *Queries) ListAlertWebhooks(ctx context.Context, allowedServers []string) ([]AlertSetting, error) {
	rows, err := q.db.Query(ctx, listAlertWebhooks, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertSetting
	for rows.Next() {
		var i AlertSetting
		if err := rows.Scan(&i.ServerName, &i.SlackWebhookUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorTokens = `-- name: ListCollectorTokens :many
SELECT id, server_name, created_at FROM collector_tokens ORDER BY created_at, id
`

type ListCollectorTokensRow struct {
	ID         int64
	ServerName string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListCollectorTokens(ctx context.Context) ([]ListCollectorTokensRow, error) {
	rows, err := q.db.Query(ctx, listCollectorTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectorTokensRow
	for rows.Next() {
		var i ListCollectorTokensRow
		if err := rows.Scan(&i.ID, &i.ServerName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockWaits = `-- name: ListLockWaits :many
WITH blocked AS (
    SELECT t.server_name, t.database_name,
           t.pid AS waiting_pid, t.application_name AS waiting_app,
           e.blocked_by_pid, e.lock_mode,
           coalesce(e.lock_wait_start, e.first_seen_at) AS wait_start,
           e.first_seen_at, e.last_seen_at,
           e.transaction_query_id, e.xact_start
    FROM transaction_events e
    JOIN transaction_queries q ON q.id = e.transaction_query_id AND q.xact_start = e.xact_start
    JOIN transactions t        ON t.id = q.transaction_id       AND t.xact_start = q.xact_start
    WHERE e.blocked_by_pid IS NOT NULL
      AND ($2::text   IS NULL OR t.server_name   = $2)
      AND ($3::text IS NULL OR t.database_name = $3)
      AND ($4::text[] IS NULL OR t.server_name = ANY($4::text[]))
      AND e.first_seen_at <= $5
      AND e.last_seen_at  >= $6
),
episodes AS (
    SELECT server_name, database_name, waiting_pid, blocked_by_pid, lock_mode, wait_start,
           max(last_seen_at)::timestamptz                                          AS last_seen,
           (array_agg(waiting_app ORDER BY first_seen_at))[1]::text                 AS waiting_app,
           (array_agg(transaction_query_id ORDER BY first_seen_at))[1]::bigint      AS waiting_query_id,
           (array_agg(xact_start ORDER BY first_seen_at))[1]::timestamptz           AS waiting_xact_start,
           CASE $7::text
               WHEN 'started' THEN extract(epoch FROM wait_start)
               ELSE extract(epoch FROM (max(last_seen_at) - wait_start))
           END AS sort_num
    FROM blocked
    GROUP BY server_name, database_name, waiting_pid, blocked_by_pid, lock_mode, wait_start
),
page AS (
    SELECT server_name, database_name, waiting_pid, waiting_app, blocked_by_pid, lock_mode,
           wait_start, last_seen, waiting_query_id, waiting_xact_start, sort_num
    FROM episodes
    ORDER BY sort_num * CASE WHEN $1::bool THEN -1 ELSE 1 END,
             wait_start DESC, server_name, database_name, waiting_pid, blocked_by_pid, lock_mode
    LIMIT $9
    OFFSET $8
)
SELECT ep.waiting_pid, ep.waiting_app,
       coalesce(wq.query, '')::text AS waiting_query,
       wq.query_tags                AS waiting_tags,
       ep.blocked_by_pid, ep.lock_mode, ep.wait_start, ep.last_seen,
       coalesce(bt.application_name, '')::text AS blocking_app,
       coalesce(bq.query, '')::text            AS blocking_query,
       bq.query_tags                           AS blocking_tags
FROM page ep
LEFT JOIN transaction_queries wq
       ON wq.id = ep.waiting_query_id AND wq.xact_start = ep.waiting_xact_start
LEFT JOIN LATERAL (
    SELECT b.id, b.xact_start, b.application_name
    FROM transactions b
    WHERE b.pid = ep.blocked_by_pid
      AND b.server_name = ep.server_name AND b.database_name = ep.database_name
      AND b.xact_start <= ep.wait_start AND b.last_seen_at >= ep.wait_start
    ORDER BY b.xact_start DESC
    LIMIT 1
) bt ON true
LEFT JOIN LATERAL (
    SELECT q2.query, q2.query_tags
    FROM transaction_queries q2
    JOIN transaction_events e2 ON e2.transaction_query_id = q2.id AND e2.xact_start = q2.xact_start
    WHERE q2.transaction_id = bt.id AND q2.xact_start = bt.xact_start
    ORDER BY (e2.first_seen_at <= ep.wait_start) DESC,
             abs(extract(epoch FROM e2.first_seen_at - ep.wait_start))
    LIMIT 1
) bq ON true
ORDER BY ep.sort_num * CASE WHEN $1::bool THEN -1 ELSE 1 END,
         ep.wait_start DESC, ep.server_name, ep.database_name,
         ep.waiting_pid, ep.blocked_by_pid, ep.lock_mode
`

type ListLockWaitsParams struct {
	SortDesc       bool
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	ToTime         pgtype.Timestamptz
	FromTime       pgtype.Timestamptz
	SortKey        string
	OffsetRows     int32
	RowLimit       int32
}

type ListLockWaitsRow struct {
	WaitingPid    int32
	WaitingApp    string
	WaitingQuery  string
	WaitingTags   []byte
	BlockedByPid  pgtype.Int4
	LockMode      pgtype.Text
	WaitStart     pgtype.Timestamptz
	LastSeen      pgtype.Timestamptz
	BlockingApp   string
	BlockingQuery string
	BlockingTags  []byte
}

func (q *Queries) ListLockWaits(ctx context.Context, arg ListLockWaitsParams) ([]ListLockWaitsRow, error) {
	rows, err := q.db.Query(ctx, listLockWaits,
		arg.SortDesc,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.ToTime,
		arg.FromTime,
		arg.SortKey,
		arg.OffsetRows,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLockWaitsRow
	for rows.Next() {
		var i ListLockWaitsRow
		if err := rows.Scan(
			&i.WaitingPid,
			&i.WaitingApp,
			&i.WaitingQuery,
			&i.WaitingTags,
			&i.BlockedByPid,
			&i.LockMode,
			&i.WaitStart,
			&i.LastSeen,
			&i.BlockingApp,
			&i.BlockingQuery,
			&i.BlockingTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEvents = `-- name: ListLogEvents :many
SELECT id, occurred_at, log_level, classification, message, pid, username,
       database_name, application_name, detail, hint, context, statement,
       backend_type, state_code, statement_sample_id
FROM (
SELECT id, occurred_at, log_level, classification, message, pid, username,
       database_name, application_name, detail, hint, context, statement,
       backend_type, state_code, statement_sample_id,
       CASE $1::text
           WHEN 'database' THEN coalesce(database_name, '')
           WHEN 'user' THEN coalesce(username, '')
       END AS sort_text,
       CASE $1::text
           WHEN 'level' THEN ($2::int[])[log_level + 1]
           WHEN 'event' THEN classification
           WHEN 'category' THEN ($3::int[])[classification + 1]
       END AS sort_num,
       CASE WHEN $1::text = 'at' THEN occurred_at END AS sort_time
FROM log_events
WHERE server_name = $4
  AND ($5::text[] IS NULL OR server_name = ANY($5::text[]))
  AND ($6::timestamptz IS NULL OR occurred_at >= $6)
  AND ($7::timestamptz IS NULL OR occurred_at <= $7)
  AND ($6::timestamptz IS NULL OR collected_at >= $6)
  AND ($8::int[] IS NULL OR log_level = ANY($8::int[]))
  AND ($9::int[] IS NULL OR classification = ANY($9::int[]))
  AND ($10::text[] IS NULL OR coalesce(database_name, '') = ANY($10::text[]))
  AND ($11::text[] IS NULL OR coalesce(username, '') = ANY($11::text[]))
  AND ($12::text[] IS NULL
       OR coalesce(application_name, '') = ANY($12::text[]))
  AND ($13::text[] IS NULL
       OR coalesce(backend_type, '') = ANY($13::text[]))
  AND ($14::text IS NULL
       OR message ILIKE '%' || $14::text || '%'
       OR detail ILIKE '%' || $14::text || '%'
       OR statement ILIKE '%' || $14::text || '%'
       OR pid::text = $14::text)
) AS sorted
ORDER BY
    CASE WHEN $15::bool THEN sort_text END DESC NULLS LAST,
    CASE WHEN NOT $15::bool THEN sort_text END ASC NULLS LAST,
    CASE WHEN $15::bool THEN sort_num END DESC NULLS LAST,
    CASE WHEN NOT $15::bool THEN sort_num END ASC NULLS LAST,
    CASE WHEN $15::bool THEN sort_time END DESC NULLS LAST,
    CASE WHEN NOT $15::bool THEN sort_time END ASC NULLS LAST,
    occurred_at DESC NULLS LAST,
    id DESC
LIMIT $17
OFFSET $16
`

type ListLogEventsParams struct {
	SortKey          string
	SeverityOf       []int32
	CategoryOf       []int32
	ServerName       string
	AllowedServers   []string
	Since            pgtype.Timestamptz
	Until            pgtype.Timestamptz
	Levels           []int32
	Classifications  []int32
	Databases        []string
	Usernames        []string
	ApplicationNames []string
	BackendTypes     []string
	Search           pgtype.Text
	SortDesc         bool
	RowOffset        int32
	RowLimit         int32
}

type ListLogEventsRow struct {
	ID                int64
	OccurredAt        pgtype.Timestamptz
	LogLevel          int32
	Classification    int32
	Message           pgtype.Text
	Pid               pgtype.Int4
	Username          pgtype.Text
	DatabaseName      pgtype.Text
	ApplicationName   pgtype.Text
	Detail            pgtype.Text
	Hint              pgtype.Text
	Context           pgtype.Text
	Statement         pgtype.Text
	BackendType       pgtype.Text
	StateCode         pgtype.Text
	StatementSampleID pgtype.Int8
}

func (q *Queries) ListLogEvents(ctx context.Context, arg ListLogEventsParams) ([]ListLogEventsRow, error) {
	rows, err := q.db.Query(ctx, listLogEvents,
		arg.SortKey,
		arg.SeverityOf,
		arg.CategoryOf,
		arg.ServerName,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
		arg.Levels,
		arg.Classifications,
		arg.Databases,
		arg.Usernames,
		arg.ApplicationNames,
		arg.BackendTypes,
		arg.Search,
		arg.SortDesc,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventsRow
	for rows.Next() {
		var i ListLogEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.LogLevel,
			&i.Classification,
			&i.Message,
			&i.Pid,
			&i.Username,
			&i.DatabaseName,
			&i.ApplicationName,
			&i.Detail,
			&i.Hint,
			&i.Context,
			&i.Statement,
			&i.BackendType,
			&i.StateCode,
			&i.StatementSampleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogStatementSamples = `-- name: ListLogStatementSamples :many
SELECT id, statement_id, query, duration_ms,
       (explain_plan_json IS NOT NULL AND explain_plan_json <> '') AS has_explain_plan
FROM statement_samples
WHERE id = ANY($1::bigint[])
  AND collected_at >= $2::timestamptz
  AND ($3::text[] IS NULL OR server_name = ANY($3::text[]))
`

type ListLogStatementSamplesParams struct {
	SampleIds      []int64
	Since          pgtype.Timestamptz
	AllowedServers []string
}

type ListLogStatementSamplesRow struct {
	ID             int64
	StatementID    pgtype.Int8
	Query          string
	DurationMs     float64
	HasExplainPlan pgtype.Bool
}

func (q *Queries) ListLogStatementSamples(ctx context.Context, arg ListLogStatementSamplesParams) ([]ListLogStatementSamplesRow, error) {
	rows, err := q.db.Query(ctx, listLogStatementSamples, arg.SampleIds, arg.Since, arg.AllowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogStatementSamplesRow
	for rows.Next() {
		var i ListLogStatementSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.StatementID,
			&i.Query,
			&i.DurationMs,
			&i.HasExplainPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoredServers = `-- name: ListMonitoredServers :many
SELECT server_name, collected_at, databases
FROM collector_health
WHERE collected_at >= now() - interval '24 hours'
  AND ($1::text[] IS NULL OR server_name = ANY($1::text[]))
ORDER BY server_name
`

func (q *Queries) ListMonitoredServers(ctx context.Context, allowedServers []string) ([]CollectorHealth, error) {
	rows, err := q.db.Query(ctx, listMonitoredServers, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectorHealth
	for rows.Next() {
		var i CollectorHealth
		if err := rows.Scan(&i.ServerName, &i.CollectedAt, &i.Databases); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersWithAlertEnabled = `-- name: ListServersWithAlertEnabled :many
SELECT s.server_name
FROM alert_settings s
LEFT JOIN alert_toggles t
  ON t.server_name = s.server_name AND t.alert_key = $1
WHERE s.slack_webhook_url <> ''
  AND coalesce(t.enabled, true)
ORDER BY s.server_name
`

func (q *Queries) ListServersWithAlertEnabled(ctx context.Context, alertKey string) ([]string, error) {
	rows, err := q.db.Query(ctx, listServersWithAlertEnabled, alertKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_name string
		if err := rows.Scan(&server_name); err != nil {
			return nil, err
		}
		items = append(items, server_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowStatements = `-- name: ListSlowStatements :many
WITH slow AS (
    SELECT d.statement_id,
           sum(d.calls)::bigint AS calls,
           (sum(d.total_exec_time) / NULLIF(sum(d.calls), 0))::double precision AS avg_ms,
           sum(d.total_exec_time) AS total_ms
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE s.server_name = $2
      AND d.collected_at >= now() - $1::interval
    GROUP BY d.statement_id
    HAVING sum(d.calls) >= $3
       AND sum(d.total_exec_time) / NULLIF(sum(d.calls), 0) >= $4
    ORDER BY sum(d.total_exec_time) DESC
    LIMIT $5
)
SELECT slow.statement_id AS id,
       slow.calls,
       slow.avg_ms,
       coalesce(st.tags, '{}'::jsonb) AS tags
FROM slow
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(per_key.key, per_key.value) AS tags
    FROM (
        SELECT kv.key, min(kv.value) AS value
        FROM statement_samples qs
        CROSS JOIN LATERAL jsonb_each_text(qs.tags) AS kv(key, value)
        WHERE qs.statement_id = slow.statement_id
          AND qs.tags IS NOT NULL
          AND kv.key NOT LIKE '%\_id'
          AND qs.collected_at >= now() - $1::interval
        GROUP BY kv.key
        HAVING count(DISTINCT kv.value) = 1
    ) per_key
) st ON true
ORDER BY slow.total_ms DESC
`

type ListSlowStatementsParams struct {
	Window     pgtype.Interval
	ServerName string
	MinCalls   int64
	MinAvgMs   float64
	MaxRows    int32
}

type ListSlowStatementsRow struct {
	ID    int64
	Calls int64
	AvgMs float64
	Tags  []byte
}

func (q *Queries) ListSlowStatements(ctx context.Context, arg ListSlowStatementsParams) ([]ListSlowStatementsRow, error) {
	rows, err := q.db.Query(ctx, listSlowStatements,
		arg.Window,
		arg.ServerName,
		arg.MinCalls,
		arg.MinAvgMs,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSlowStatementsRow
	for rows.Next() {
		var i ListSlowStatementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Calls,
			&i.AvgMs,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleServers = `-- name: ListStaleServers :many
SELECT server_name
FROM collector_health
WHERE collected_at < now() - $1::interval
  AND collected_at >= now() - interval '24 hours'
ORDER BY server_name
`

func (q *Queries) ListStaleServers(ctx context.Context, staleAfter pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleServers, staleAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_name string
		if err := rows.Scan(&server_name); err != nil {
			return nil, err
		}
		items = append(items, server_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementSamples = `-- name: ListStatementSamples :many
WITH filtered AS (
    SELECT id, occurred_at, query, duration_ms, parameters, explain_plan_json, tags,
        CASE WHEN $4::text = 'at' THEN s.occurred_at END AS sort_time,
        CASE $4::text
            WHEN 'duration' THEN s.duration_ms
            WHEN 'plan' THEN (s.explain_plan_json IS NOT NULL)::int::double precision
        END AS sort_num
    FROM statement_samples s
    WHERE s.statement_id = $5
      AND ($6::text[] IS NULL OR s.server_name = ANY($6::text[]))
      AND ($7::timestamptz IS NULL OR s.collected_at >= $7)
      AND ($8::timestamptz IS NULL OR s.collected_at <= $8)
      AND NOT (
          -- Drop this log_min_duration row when auto_explain logged the same run.
          s.explain_plan_json IS NULL
          AND EXISTS (
              SELECT 1
              FROM statement_samples e
              WHERE e.statement_id = s.statement_id
                AND e.explain_plan_json IS NOT NULL
                AND e.query = s.query
                AND e.parameters IS NOT DISTINCT FROM s.parameters
                AND e.tags IS NOT DISTINCT FROM s.tags
                AND e.occurred_at BETWEEN s.occurred_at - interval '1 second'
                                      AND s.occurred_at + interval '1 second'
                AND s.duration_ms >= e.duration_ms - 50
                AND ($7::timestamptz IS NULL OR e.collected_at >= $7)
                AND ($8::timestamptz IS NULL OR e.collected_at <= $8)
          )
      )
)
SELECT id, occurred_at, query, duration_ms, parameters, explain_plan_json, tags
FROM filtered
ORDER BY
    CASE WHEN $1::bool THEN sort_time END DESC NULLS LAST,
    CASE WHEN NOT $1::bool THEN sort_time END ASC NULLS LAST,
    CASE WHEN $1::bool THEN sort_num END DESC,
    CASE WHEN NOT $1::bool THEN sort_num END ASC,
    id DESC
LIMIT $3
OFFSET $2
`

type ListStatementSamplesParams struct {
	SortDesc       bool
	OffsetRows     int32
	RowLimit       int32
	SortKey        string
	StatementID    pgtype.Int8
	AllowedServers []string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
}

type ListStatementSamplesRow struct {
	ID              int64
	OccurredAt      pgtype.Timestamptz
	Query           string
	DurationMs      float64
	Parameters      []string
	ExplainPlanJson pgtype.Text
	Tags            []byte
}

func (q *Queries) ListStatementSamples(ctx context.Context, arg ListStatementSamplesParams) ([]ListStatementSamplesRow, error) {
	rows, err := q.db.Query(ctx, listStatementSamples,
		arg.SortDesc,
		arg.OffsetRows,
		arg.RowLimit,
		arg.SortKey,
		arg.StatementID,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementSamplesRow
	for rows.Next() {
		var i ListStatementSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Query,
			&i.DurationMs,
			&i.Parameters,
			&i.ExplainPlanJson,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementStats = `-- name: ListStatementStats :many
WITH scoped AS (
    SELECT s.id
    FROM statements s
    WHERE ($4::text IS NULL OR s.server_name = $4)
      AND ($5::text IS NULL OR s.database_name = $5)
      AND ($6::text[] IS NULL OR s.server_name = ANY($6::text[]))
),
per_all AS (
    SELECT
        d.statement_id,
        sum(d.calls)::bigint                     AS calls,
        sum(d.rows)::bigint                      AS rows,
        sum(d.total_exec_time)::double precision AS total_exec_time,
        sum(d.total_io_time)::double precision   AS total_io_time
    FROM statement_deltas d
    WHERE d.statement_id IN (SELECT id FROM scoped)
      AND ($1::timestamptz IS NULL OR d.collected_at >= $1)
      AND ($2::timestamptz IS NULL OR d.collected_at <= $2)
    GROUP BY d.statement_id
),
totals AS (
    SELECT
        sum(total_exec_time)::double precision AS total_exec_time,
        sum(total_io_time)::double precision   AS total_io_time
    FROM per_all
),
filtered AS (
    SELECT
        pa.statement_id AS id,
        s.query_short   AS preview,
        s.user_name,
        pa.calls,
        pa.rows,
        pa.total_exec_time,
        pa.total_io_time,
        CASE $7::text
            WHEN 'query' THEN s.query_short
            WHEN 'user' THEN s.user_name
        END AS sort_text,
        CASE $7::text
            WHEN 'avg' THEN pa.total_exec_time / NULLIF(pa.calls, 0)
            WHEN 'calls' THEN pa.calls::double precision
            WHEN 'rows_per_call' THEN pa.rows::double precision / NULLIF(pa.calls, 0)
            WHEN 'pct_io' THEN pa.total_io_time
            ELSE pa.total_exec_time
        END AS sort_num
    FROM per_all pa
    JOIN statements s ON s.id = pa.statement_id
    WHERE ($8::text IS NULL
           OR s.query_full ILIKE '%' || $8::text || '%')
      AND ($9::bigint[] IS NULL
           OR s.id = ANY($9::bigint[]))
      AND s.query_kind = ANY($10::int[])
),
page AS (
    SELECT id, preview, user_name, calls, rows, total_exec_time, total_io_time, sort_text, sort_num
    FROM filtered
    ORDER BY
        CASE WHEN $3::bool THEN sort_text END DESC,
        CASE WHEN NOT $3::bool THEN sort_text END ASC,
        CASE WHEN $3::bool THEN sort_num END DESC,
        CASE WHEN NOT $3::bool THEN sort_num END ASC,
        id DESC
    LIMIT $12
    OFFSET $11
)
SELECT
    p.id,
    p.preview,
    p.user_name,
    p.calls,
    p.rows,
    p.total_exec_time,
    (coalesce(p.total_exec_time / NULLIF((SELECT total_exec_time FROM totals), 0), 0) * 100)::double precision AS pct_of_total,
    (coalesce(p.total_io_time / NULLIF((SELECT total_io_time FROM totals), 0), 0) * 100)::double precision AS pct_io,
    coalesce(st.tags, '{}'::jsonb) AS tags
FROM page p
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(per_key.key, per_key.value) AS tags
    FROM (
        SELECT kv.key, min(kv.value) AS value
        FROM (
            SELECT DISTINCT qs.tags
            FROM statement_samples qs
            WHERE qs.statement_id = p.id
              AND qs.tags IS NOT NULL
              AND ($1::timestamptz IS NULL OR qs.collected_at >= $1)
              AND ($2::timestamptz IS NULL OR qs.collected_at <= $2)
        ) dt
        CROSS JOIN LATERAL jsonb_each_text(dt.tags) AS kv(key, value)
        WHERE kv.key NOT LIKE '%\_id'
        GROUP BY kv.key
        HAVING min(kv.value) = max(kv.value)
    ) per_key
) st ON true
ORDER BY
    CASE WHEN $3::bool THEN p.sort_text END DESC,
    CASE WHEN NOT $3::bool THEN p.sort_text END ASC,
    CASE WHEN $3::bool THEN p.sort_num END DESC,
    CASE WHEN NOT $3::bool THEN p.sort_num END ASC,
    p.id DESC
`

type ListStatementStatsParams struct {
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	SortDesc       bool
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	SortKey        string
	TextFilter     pgtype.Text
	StatementIds   []int64
	Kinds          []int32
	OffsetRows     int32
	RowLimit       int32
}

type ListStatementStatsRow struct {
	ID            int64
	Preview       string
	UserName      string
	Calls         int64
	Rows          int64
	TotalExecTime float64
	PctOfTotal    float64
	PctIo         float64
	Tags          []byte
}

func (q *Queries) ListStatementStats(ctx context.Context, arg ListStatementStatsParams) ([]ListStatementStatsRow, error) {
	rows, err := q.db.Query(ctx, listStatementStats,
		arg.Since,
		arg.Until,
		arg.SortDesc,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.SortKey,
		arg.TextFilter,
		arg.StatementIds,
		arg.Kinds,
		arg.OffsetRows,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementStatsRow
	for rows.Next() {
		var i ListStatementStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Preview,
			&i.UserName,
			&i.Calls,
			&i.Rows,
			&i.TotalExecTime,
			&i.PctOfTotal,
			&i.PctIo,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementsMissingText = `-- name: ListStatementsMissingText :many
SELECT user_name, database_name, query_id
FROM statements
WHERE id = ANY($1::bigint[])
  AND query_full = ''
`

type ListStatementsMissingTextRow struct {
	UserName     string
	DatabaseName string
	QueryID      int64
}

func (q *Queries) ListStatementsMissingText(ctx context.Context, ids []int64) ([]ListStatementsMissingTextRow, error) {
	rows, err := q.db.Query(ctx, listStatementsMissingText, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsMissingTextRow
	for rows.Next() {
		var i ListStatementsMissingTextRow
		if err := rows.Scan(&i.UserName, &i.DatabaseName, &i.QueryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagKeys = `-- name: ListTagKeys :many
WITH agreed AS (
    SELECT ss.statement_id, kv.key, min(kv.value) AS value
    FROM statement_samples ss
    JOIN statements s ON s.id = ss.statement_id
    CROSS JOIN LATERAL jsonb_each_text(ss.tags) AS kv(key, value)
    WHERE ss.tags IS NOT NULL
      AND ss.statement_id IS NOT NULL
      AND kv.key NOT LIKE '%\_id'
      AND ss.collected_at >= $1::timestamptz
      AND ss.collected_at <= $2::timestamptz
      AND ($3::text IS NULL OR ss.server_name = $3)
      AND ($4::text IS NULL OR s.database_name = $4)
      AND ($5::text[] IS NULL OR ss.server_name = ANY($5::text[]))
    GROUP BY ss.statement_id, kv.key
    HAVING count(DISTINCT kv.value) = 1
)
SELECT
    key::text                     AS key,
    count(DISTINCT value)::bigint AS value_count
FROM agreed
GROUP BY key
ORDER BY count(DISTINCT statement_id) DESC, key
`

type ListTagKeysParams struct {
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type ListTagKeysRow struct {
	Key        string
	ValueCount int64
}

func (q *Queries) ListTagKeys(ctx context.Context, arg ListTagKeysParams) ([]ListTagKeysRow, error) {
	rows, err := q.db.Query(ctx, listTagKeys,
		arg.Since,
		arg.Until,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagKeysRow
	for rows.Next() {
		var i ListTagKeysRow
		if err := rows.Scan(&i.Key, &i.ValueCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagValues = `-- name: ListTagValues :many
WITH agreed AS (
    SELECT
        ss.statement_id,
        min(ss.tags ->> $1::text) AS value
    FROM statement_samples ss
    JOIN statements s ON s.id = ss.statement_id
    WHERE ss.tags ? $1::text
      AND $1::text NOT LIKE '%\_id'
      AND ss.statement_id IS NOT NULL
      AND ss.collected_at >= $2::timestamptz
      AND ss.collected_at <= $3::timestamptz
      AND ($4::text IS NULL OR ss.server_name = $4)
      AND ($5::text IS NULL OR s.database_name = $5)
      AND ($6::text[] IS NULL OR ss.server_name = ANY($6::text[]))
    GROUP BY ss.statement_id
    HAVING count(DISTINCT ss.tags ->> $1::text) = 1
)
SELECT
    value::text                          AS value,
    count(DISTINCT statement_id)::bigint AS statement_count
FROM agreed
GROUP BY value
ORDER BY statement_count DESC, value
`

type ListTagValuesParams struct {
	TagKey         string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type ListTagValuesRow struct {
	Value          string
	StatementCount int64
}

func (q *Queries) ListTagValues(ctx context.Context, arg ListTagValuesParams) ([]ListTagValuesRow, error) {
	rows, err := q.db.Query(ctx, listTagValues,
		arg.TagKey,
		arg.Since,
		arg.Until,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagValuesRow
	for rows.Next() {
		var i ListTagValuesRow
		if err := rows.Scan(&i.Value, &i.StatementCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEvents = `-- name: ListTransactionEvents :many
SELECT q.transaction_id, e.state, e.wait_event_type, e.wait_event, e.lock_mode,
       q.query, q.query_tags, q.query_start, e.first_seen_at, e.last_seen_at
FROM transaction_events e
JOIN transaction_queries q ON q.id = e.transaction_query_id AND q.xact_start = e.xact_start
JOIN transactions t        ON t.id = q.transaction_id       AND t.xact_start = q.xact_start
WHERE q.transaction_id = ANY($1::bigint[])
  AND ($2::text[] IS NULL OR t.server_name = ANY($2::text[]))
ORDER BY q.transaction_id, e.first_seen_at, e.id
`

type ListTransactionEventsParams struct {
	TransactionIds []int64
	AllowedServers []string
}

type ListTransactionEventsRow struct {
	TransactionID int64
	State         string
	WaitEventType pgtype.Text
	WaitEvent     pgtype.Text
	LockMode      pgtype.Text
	Query         string
	QueryTags     []byte
	QueryStart    pgtype.Timestamptz
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

func (q *Queries) ListTransactionEvents(ctx context.Context, arg ListTransactionEventsParams) ([]ListTransactionEventsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEvents, arg.TransactionIds, arg.AllowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionEventsRow
	for rows.Next() {
		var i ListTransactionEventsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.State,
			&i.WaitEventType,
			&i.WaitEvent,
			&i.LockMode,
			&i.Query,
			&i.QueryTags,
			&i.QueryStart,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
WITH filtered AS (
    SELECT id, pid, application_name, xact_start, last_seen_at,
           CASE $4::text
               WHEN 'started' THEN extract(epoch FROM xact_start)
               ELSE extract(epoch FROM (last_seen_at - xact_start))
           END AS sort_num
    FROM transactions
    WHERE ($5::text   IS NULL OR server_name   = $5)
      AND ($6::text IS NULL OR database_name = $6)
      AND ($7::text[] IS NULL OR server_name = ANY($7::text[]))
      AND xact_start   <= $8
      AND last_seen_at >= $9
      AND last_seen_at - xact_start >= $10::interval
)
SELECT id, pid, application_name, xact_start, last_seen_at
FROM filtered
ORDER BY
    CASE WHEN $1::bool THEN sort_num END DESC,
    CASE WHEN NOT $1::bool THEN sort_num END ASC,
    id DESC
LIMIT $3
OFFSET $2
`

type ListTransactionsParams struct {
	SortDesc       bool
	OffsetRows     int32
	RowLimit       int32
	SortKey        string
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	ToTime         pgtype.Timestamptz
	FromTime       pgtype.Timestamptz
	MinOpen        pgtype.Interval
}

type ListTransactionsRow struct {
	ID              int64
	Pid             int32
	ApplicationName string
	XactStart       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.SortDesc,
		arg.OffsetRows,
		arg.RowLimit,
		arg.SortKey,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.ToTime,
		arg.FromTime,
		arg.MinOpen,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.ApplicationName,
			&i.XactStart,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, is_super_admin, created_at, allowed_servers
FROM users
ORDER BY created_at, id
`

type ListUsersRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsSuperAdmin,
			&i.CreatedAt,
			&i.AllowedServers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWaitSeries = `-- name: LockWaitSeries :many
WITH waits AS (
    SELECT t.server_name, t.database_name, t.pid AS waiting_pid,
           e.blocked_by_pid, e.lock_mode,
           coalesce(e.lock_wait_start, e.first_seen_at) AS wait_start,
           e.last_seen_at
    FROM transaction_events e
    JOIN transaction_queries q ON q.id = e.transaction_query_id AND q.xact_start = e.xact_start
    JOIN transactions t        ON t.id = q.transaction_id       AND t.xact_start = q.xact_start
    WHERE e.blocked_by_pid IS NOT NULL
      AND ($1::text   IS NULL OR t.server_name   = $1)
      AND ($2::text IS NULL OR t.database_name = $2)
      AND ($3::text[] IS NULL OR t.server_name = ANY($3::text[]))
      AND e.first_seen_at <= $4::timestamptz
      AND e.last_seen_at  >  $5::timestamptz
),
episodes AS (
    SELECT wait_start, max(last_seen_at)::timestamptz AS last_seen
    FROM waits
    GROUP BY server_name, database_name, waiting_pid, blocked_by_pid, lock_mode, wait_start
),
spread AS (
    SELECT b.bucket_end,
           sum(extract(epoch FROM (
               LEAST(w.last_seen, b.bucket_end)
               - GREATEST(w.wait_start, b.bucket_end - $6::interval)
           ))) AS wait_seconds
    FROM episodes w
    CROSS JOIN LATERAL generate_series(
        date_bin($6::interval, w.wait_start - interval '1 microsecond',
                 $7::timestamptz) + $6::interval,
        date_bin($6::interval, w.last_seen - interval '1 microsecond',
                 $7::timestamptz) + $6::interval,
        $6::interval
    ) AS b(bucket_end)
    WHERE b.bucket_end >  $5::timestamptz
      AND b.bucket_end <= $7::timestamptz
    GROUP BY b.bucket_end
)
SELECT bucket_end::timestamptz        AS bucket_end,
       wait_seconds::double precision AS wait_seconds
FROM spread
ORDER BY bucket_end
`

type LockWaitSeriesParams struct {
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	RangeEnd       pgtype.Timestamptz
	RangeStart     pgtype.Timestamptz
	Bucket         pgtype.Interval
	Anchor         pgtype.Timestamptz
}

type LockWaitSeriesRow struct {
	BucketEnd   pgtype.Timestamptz
	WaitSeconds float64
}

func (q *Queries) LockWaitSeries(ctx context.Context, arg LockWaitSeriesParams) ([]LockWaitSeriesRow, error) {
	rows, err := q.db.Query(ctx, lockWaitSeries,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.RangeEnd,
		arg.RangeStart,
		arg.Bucket,
		arg.Anchor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockWaitSeriesRow
	for rows.Next() {
		var i LockWaitSeriesRow
		if err := rows.Scan(&i.BucketEnd, &i.WaitSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logEventFacets = `-- name: LogEventFacets :many
WITH matched AS (
    SELECT classification,
           log_level,
           coalesce(database_name, '') AS database_name,
           coalesce(username, '') AS username,
           coalesce(application_name, '') AS application_name,
           coalesce(backend_type, '') AS backend_type
    FROM log_events
    WHERE server_name = $1
      AND occurred_at >= $2::timestamptz
      AND occurred_at <= $3::timestamptz
      AND collected_at >= $2::timestamptz
      AND ($4::text[] IS NULL
           OR server_name = ANY($4::text[]))
      AND ($5::int[] IS NULL
           OR classification = ANY($5::int[]))
      AND ($6::text[] IS NULL
           OR coalesce(database_name, '') = ANY($6::text[]))
      AND ($7::text[] IS NULL
           OR coalesce(username, '') = ANY($7::text[]))
      AND ($8::text[] IS NULL
           OR coalesce(application_name, '') = ANY($8::text[]))
      AND ($9::text[] IS NULL
           OR coalesce(backend_type, '') = ANY($9::text[]))
      AND ($10::text IS NULL
           OR message ILIKE '%' || $10::text || '%'
           OR detail ILIKE '%' || $10::text || '%'
           OR statement ILIKE '%' || $10::text || '%'
           OR pid::text = $10::text)
)
SELECT grouping(classification, log_level, database_name, username,
                application_name, backend_type)::int AS grouping_id,
       coalesce(classification, 0)::int AS classification,
       coalesce(log_level, 0)::int AS log_level,
       coalesce(database_name, '')::text AS database_name,
       coalesce(username, '')::text AS username,
       coalesce(application_name, '')::text AS application_name,
       coalesce(backend_type, '')::text AS backend_type,
       count(*)::bigint AS n
FROM matched
GROUP BY GROUPING SETS (
    (classification),
    (log_level),
    (database_name),
    (username),
    (application_name),
    (backend_type)
)
ORDER BY 1, 8 DESC
`

type LogEventFacetsParams struct {
	ServerName       string
	Since            pgtype.Timestamptz
	Until            pgtype.Timestamptz
	AllowedServers   []string
	Classifications  []int32
	Databases        []string
	Usernames        []string
	ApplicationNames []string
	BackendTypes     []string
	Search           pgtype.Text
}

type LogEventFacetsRow struct {
	GroupingID      int32
	Classification  int32
	LogLevel        int32
	DatabaseName    string
	Username        string
	ApplicationName string
	BackendType     string
	N               int64
}

func (q *Queries) LogEventFacets(ctx context.Context, arg LogEventFacetsParams) ([]LogEventFacetsRow, error) {
	rows, err := q.db.Query(ctx, logEventFacets,
		arg.ServerName,
		arg.Since,
		arg.Until,
		arg.AllowedServers,
		arg.Classifications,
		arg.Databases,
		arg.Usernames,
		arg.ApplicationNames,
		arg.BackendTypes,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEventFacetsRow
	for rows.Next() {
		var i LogEventFacetsRow
		if err := rows.Scan(
			&i.GroupingID,
			&i.Classification,
			&i.LogLevel,
			&i.DatabaseName,
			&i.Username,
			&i.ApplicationName,
			&i.BackendType,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logEventHistogram = `-- name: LogEventHistogram :many
SELECT (date_bin($1::interval, occurred_at - interval '1 microsecond',
                 $2::timestamptz) + $1::interval)::timestamptz AS bucket_end,
       log_level,
       classification,
       count(*)::bigint AS n
FROM log_events
WHERE server_name = $3
  AND occurred_at IS NOT NULL
  AND occurred_at >  $4::timestamptz
  AND occurred_at <= $2::timestamptz
  AND collected_at >= $4::timestamptz
  AND ($5::text[] IS NULL OR server_name = ANY($5::text[]))
  AND ($6::int[] IS NULL OR classification = ANY($6::int[]))
  AND ($7::text[] IS NULL OR coalesce(database_name, '') = ANY($7::text[]))
  AND ($8::text[] IS NULL OR coalesce(username, '') = ANY($8::text[]))
  AND ($9::text[] IS NULL
       OR coalesce(application_name, '') = ANY($9::text[]))
  AND ($10::text[] IS NULL
       OR coalesce(backend_type, '') = ANY($10::text[]))
  AND ($11::text IS NULL
       OR message ILIKE '%' || $11::text || '%'
       OR detail ILIKE '%' || $11::text || '%'
       OR statement ILIKE '%' || $11::text || '%'
       OR pid::text = $11::text)
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3
`

type LogEventHistogramParams struct {
	Bucket           pgtype.Interval
	Anchor           pgtype.Timestamptz
	ServerName       string
	Since            pgtype.Timestamptz
	AllowedServers   []string
	Classifications  []int32
	Databases        []string
	Usernames        []string
	ApplicationNames []string
	BackendTypes     []string
	Search           pgtype.Text
}

type LogEventHistogramRow struct {
	BucketEnd      pgtype.Timestamptz
	LogLevel       int32
	Classification int32
	N              int64
}

func (q *Queries) LogEventHistogram(ctx context.Context, arg LogEventHistogramParams) ([]LogEventHistogramRow, error) {
	rows, err := q.db.Query(ctx, logEventHistogram,
		arg.Bucket,
		arg.Anchor,
		arg.ServerName,
		arg.Since,
		arg.AllowedServers,
		arg.Classifications,
		arg.Databases,
		arg.Usernames,
		arg.ApplicationNames,
		arg.BackendTypes,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEventHistogramRow
	for rows.Next() {
		var i LogEventHistogramRow
		if err := rows.Scan(
			&i.BucketEnd,
			&i.LogLevel,
			&i.Classification,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAlertFires = `-- name: PruneAlertFires :exec
DELETE FROM alert_fires WHERE fired_at < now() - $1::interval
`

func (q *Queries) PruneAlertFires(ctx context.Context, historyWindow pgtype.Interval) error {
	_, err := q.db.Exec(ctx, pruneAlertFires, historyWindow)
	return err
}

const removeServerFromUsers = `-- name: RemoveServerFromUsers :exec
UPDATE users SET allowed_servers = array_remove(allowed_servers, $1::text)
`

func (q *Queries) RemoveServerFromUsers(ctx context.Context, serverName string) error {
	_, err := q.db.Exec(ctx, removeServerFromUsers, serverName)
	return err
}

const rollupStatementLatencyBins = `-- name: RollupStatementLatencyBins :exec
WITH cleared AS (
    DELETE FROM statement_latency_bins
    WHERE minute_start >= $1::timestamptz
      AND minute_start <  $2::timestamptz
    RETURNING 1
),
binned AS (
    SELECT date_trunc('minute', d.collected_at - interval '1 microsecond') AS minute_start,
           s.server_name,
           s.database_name,
           floor(ln(greatest(d.total_exec_time / d.calls, 0.001)) / ln(1.01))::smallint AS bin,
           sum(d.calls)::integer AS weight
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $1::timestamptz
      AND d.collected_at <= $2::timestamptz
      AND d.calls > 0
      AND s.query_kind <> $3::int
      AND (SELECT count(*) FROM cleared) >= 0
    GROUP BY 1, 2, 3, 4
)
INSERT INTO statement_latency_bins (minute_start, server_name, database_name, bins, weights)
SELECT minute_start, server_name, database_name,
       array_agg(bin ORDER BY bin), array_agg(weight ORDER BY bin)
FROM binned
GROUP BY minute_start, server_name, database_name
`

type RollupStatementLatencyBinsParams struct {
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	UtilityKind int32
}

// Turns raw deltas from a time range into one summed latency histogram per minute.
func (q *Queries) RollupStatementLatencyBins(ctx context.Context, arg RollupStatementLatencyBinsParams) error {
	_, err := q.db.Exec(ctx, rollupStatementLatencyBins, arg.RangeStart, arg.RangeEnd, arg.UtilityKind)
	return err
}

const statementLatencyBins = `-- name: StatementLatencyBins :many
SELECT minute_start, bins, weights
FROM statement_latency_bins
WHERE minute_start >= $1::timestamptz
  AND minute_start <  $2::timestamptz
  AND ($3::text IS NULL OR server_name = $3)
  AND ($4::text IS NULL OR database_name = $4)
  AND ($5::text[] IS NULL
       OR server_name = ANY($5::text[]))
`

type StatementLatencyBinsParams struct {
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type StatementLatencyBinsRow struct {
	MinuteStart pgtype.Timestamptz
	Bins        []int16
	Weights     []int32
}

// Fetches those ready-made histograms for the chart's time window.
func (q *Queries) StatementLatencyBins(ctx context.Context, arg StatementLatencyBinsParams) ([]StatementLatencyBinsRow, error) {
	rows, err := q.db.Query(ctx, statementLatencyBins,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementLatencyBinsRow
	for rows.Next() {
		var i StatementLatencyBinsRow
		if err := rows.Scan(&i.MinuteStart, &i.Bins, &i.Weights); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementLatencyRollupResume = `-- name: StatementLatencyRollupResume :one
SELECT coalesce(
    (SELECT max(minute_start) FROM statement_latency_bins),
    (SELECT min(collected_at) FROM statement_deltas),
    now()
)::timestamptz AS resume_from
`

// The last minute already written, so the rollup job knows where to resume.
func (q *Queries) StatementLatencyRollupResume(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, statementLatencyRollupResume)
	var resume_from pgtype.Timestamptz
	err := row.Scan(&resume_from)
	return resume_from, err
}

const statementLatencyTailBins = `-- name: StatementLatencyTailBins :many
WITH binned AS (
    SELECT date_trunc('minute', d.collected_at - interval '1 microsecond') AS minute_start,
           floor(ln(greatest(d.total_exec_time / d.calls, 0.001)) / ln(1.01))::smallint AS bin,
           sum(d.calls)::integer AS weight
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $1::timestamptz + interval '1 minute'
      AND d.collected_at <= $2::timestamptz
      AND d.calls > 0
      AND s.query_kind <> $3::int
      AND ($4::text IS NULL OR s.server_name = $4)
      AND ($5::text IS NULL OR s.database_name = $5)
      AND ($6::text[] IS NULL
           OR s.server_name = ANY($6::text[]))
    GROUP BY 1, 2
)
SELECT minute_start::timestamptz AS minute_start,
       array_agg(bin ORDER BY bin)::smallint[]   AS bins,
       array_agg(weight ORDER BY bin)::integer[] AS weights
FROM binned
GROUP BY minute_start
`

type StatementLatencyTailBinsParams struct {
	TailStart      pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	UtilityKind    int32
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type StatementLatencyTailBinsRow struct {
	MinuteStart pgtype.Timestamptz
	Bins        []int16
	Weights     []int32
}

// Fills the last minute or two the writer hasn't reached yet, straight from raw deltas, so fresh data still shows up.
func (q *Queries) StatementLatencyTailBins(ctx context.Context, arg StatementLatencyTailBinsParams) ([]StatementLatencyTailBinsRow, error) {
	rows, err := q.db.Query(ctx, statementLatencyTailBins,
		arg.TailStart,
		arg.RangeEnd,
		arg.UtilityKind,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementLatencyTailBinsRow
	for rows.Next() {
		var i StatementLatencyTailBinsRow
		if err := rows.Scan(&i.MinuteStart, &i.Bins, &i.Weights); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementMetricSeries = `-- name: StatementMetricSeries :many
WITH scoped AS (
    SELECT
        date_bin($1::interval,
                 d.collected_at - interval '1 microsecond',
                 $2::timestamptz) + $1::interval AS bucket_end,
        d.total_exec_time,
        d.total_io_time,
        d.calls,
        (($3::text IS NULL OR s.database_name = $3)
         AND ($4::bigint IS NULL OR d.statement_id = $4)
         AND ($5::text IS NULL
              OR s.query_full ILIKE '%' || $5::text || '%')
         AND ($6::bigint[] IS NULL
              OR d.statement_id = ANY($6::bigint[]))) AS matched
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $7::timestamptz
      AND d.collected_at <= $8::timestamptz
      AND ($9::text IS NULL OR s.server_name = $9)
      AND ($10::text[] IS NULL
           OR s.server_name = ANY($10::text[]))
)
SELECT
    bucket_end::timestamptz AS bucket_end,
    coalesce(sum(total_exec_time) FILTER (WHERE matched), 0)::double precision AS total_exec_time,
    coalesce(sum(total_io_time) FILTER (WHERE matched), 0)::double precision   AS total_io_time,
    coalesce(sum(calls) FILTER (WHERE matched), 0)::bigint                     AS calls
FROM scoped
GROUP BY bucket_end
ORDER BY bucket_end
`

type StatementMetricSeriesParams struct {
	Bucket         pgtype.Interval
	Anchor         pgtype.Timestamptz
	DatabaseName   pgtype.Text
	StatementID    pgtype.Int8
	TextFilter     pgtype.Text
	StatementIds   []int64
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	ServerName     pgtype.Text
	AllowedServers []string
}

type StatementMetricSeriesRow struct {
	BucketEnd     pgtype.Timestamptz
	TotalExecTime float64
	TotalIoTime   float64
	Calls         int64
}

func (q *Queries) StatementMetricSeries(ctx context.Context, arg StatementMetricSeriesParams) ([]StatementMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, statementMetricSeries,
		arg.Bucket,
		arg.Anchor,
		arg.DatabaseName,
		arg.StatementID,
		arg.TextFilter,
		arg.StatementIds,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ServerName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementMetricSeriesRow
	for rows.Next() {
		var i StatementMetricSeriesRow
		if err := rows.Scan(
			&i.BucketEnd,
			&i.TotalExecTime,
			&i.TotalIoTime,
			&i.Calls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transactionAgeSeries = `-- name: TransactionAgeSeries :many
SELECT (date_bin($1::interval, t.last_seen_at - interval '1 microsecond',
                 $2::timestamptz) + $1::interval)::timestamptz AS bucket_end,
       max(extract(epoch FROM (t.last_seen_at - t.xact_start)))::double precision AS ended_age,
       min(t.xact_start)::timestamptz AS oldest_start
FROM transactions t
WHERE ($3::text   IS NULL OR t.server_name   = $3)
  AND ($4::text IS NULL OR t.database_name = $4)
  AND ($5::text[] IS NULL OR t.server_name = ANY($5::text[]))
  AND t.xact_start   <= $6::timestamptz
  AND t.last_seen_at >  $7::timestamptz
GROUP BY 1
ORDER BY 1
`

type TransactionAgeSeriesParams struct {
	Bucket         pgtype.Interval
	Anchor         pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	RangeEnd       pgtype.Timestamptz
	RangeStart     pgtype.Timestamptz
}

type TransactionAgeSeriesRow struct {
	BucketEnd   pgtype.Timestamptz
	EndedAge    float64
	OldestStart pgtype.Timestamptz
}

func (q *Queries) TransactionAgeSeries(ctx context.Context, arg TransactionAgeSeriesParams) ([]TransactionAgeSeriesRow, error) {
	rows, err := q.db.Query(ctx, transactionAgeSeries,
		arg.Bucket,
		arg.Anchor,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.RangeEnd,
		arg.RangeStart,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionAgeSeriesRow
	for rows.Next() {
		var i TransactionAgeSeriesRow
		if err := rows.Scan(&i.BucketEnd, &i.EndedAge, &i.OldestStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryClaimAlertNotification = `-- name: TryClaimAlertNotification :one
WITH claimed AS (
    INSERT INTO alert_notifications (server_name, alert_key, last_fired_at)
    VALUES ($1, $2, now())
    ON CONFLICT (server_name, alert_key)
    DO UPDATE SET last_fired_at = now()
    WHERE alert_notifications.last_fired_at < now() - $3::interval
    RETURNING last_fired_at
),
recorded AS (
    INSERT INTO alert_fires (server_name, alert_key, fired_at)
    SELECT $1, $2, claimed.last_fired_at
    FROM claimed
)
SELECT last_fired_at FROM claimed
`

type TryClaimAlertNotificationParams struct {
	ServerName string
	AlertKey   string
	Cooldown   pgtype.Interval
}

func (q *Queries) TryClaimAlertNotification(ctx context.Context, arg TryClaimAlertNotificationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, tryClaimAlertNotification, arg.ServerName, arg.AlertKey, arg.Cooldown)
	var last_fired_at pgtype.Timestamptz
	err := row.Scan(&last_fired_at)
	return last_fired_at, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    email = $2,
    password_hash = coalesce($3::text, password_hash),
    allowed_servers = $4
WHERE id = $5
RETURNING id, name, email, is_super_admin, created_at, allowed_servers
`

type UpdateUserParams struct {
	Name           string
	Email          string
	PasswordHash   pgtype.Text
	AllowedServers []string
	ID             int64
}

type UpdateUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.AllowedServers,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const upsertAlertWebhook = `-- name: UpsertAlertWebhook :exec
INSERT INTO alert_settings (server_name, slack_webhook_url)
VALUES ($1, $2)
ON CONFLICT (server_name) DO UPDATE SET slack_webhook_url = EXCLUDED.slack_webhook_url
`

type UpsertAlertWebhookParams struct {
	ServerName      string
	SlackWebhookUrl string
}

func (q *Queries) UpsertAlertWebhook(ctx context.Context, arg UpsertAlertWebhookParams) error {
	_, err := q.db.Exec(ctx, upsertAlertWebhook, arg.ServerName, arg.SlackWebhookUrl)
	return err
}

const upsertCollectorHealth = `-- name: UpsertCollectorHealth :exec
INSERT INTO collector_health (server_name, collected_at, databases)
VALUES ($1, $2, $3)
ON CONFLICT (server_name) DO UPDATE
SET collected_at = EXCLUDED.collected_at,
    databases = EXCLUDED.databases
`

type UpsertCollectorHealthParams struct {
	ServerName  string
	CollectedAt pgtype.Timestamptz
	Databases   []string
}

func (q *Queries) UpsertCollectorHealth(ctx context.Context, arg UpsertCollectorHealthParams) error {
	_, err := q.db.Exec(ctx, upsertCollectorHealth, arg.ServerName, arg.CollectedAt, arg.Databases)
	return err
}

const weeklyReportSummary = `-- name: WeeklyReportSummary :one
WITH binned AS (
    SELECT CASE WHEN minute_start >= now() - interval '7 days' THEN 'current' ELSE 'previous' END AS period,
           unnest(bins) AS bin,
           unnest(weights) AS weight
    FROM statement_latency_bins
    WHERE server_name = $1
      AND minute_start >= now() - interval '14 days'
),
per_bin AS (
    SELECT period, bin, sum(weight)::bigint AS weight
    FROM binned
    GROUP BY period, bin
),
running AS (
    SELECT period, bin,
           sum(weight) OVER (PARTITION BY period ORDER BY bin) AS below,
           sum(weight) OVER (PARTITION BY period) AS total
    FROM per_bin
),
p99 AS (
    SELECT period, exp((min(bin) + 0.5) * ln(1.01)) AS ms
    FROM running
    WHERE below >= 0.99 * total
    GROUP BY period
)
SELECT
    coalesce((SELECT ms FROM p99 WHERE period = 'current'), 0)::double precision AS p99_current,
    coalesce((SELECT ms FROM p99 WHERE period = 'previous'), 0)::double precision AS p99_previous,
    (SELECT coalesce(sum(d.calls), 0)::bigint
       FROM statement_deltas d JOIN statements s ON s.id = d.statement_id
       WHERE s.server_name = $1
         AND d.collected_at >= now() - interval '7 days') AS calls_current,
    (SELECT coalesce(sum(d.calls), 0)::bigint
       FROM statement_deltas d JOIN statements s ON s.id = d.statement_id
       WHERE s.server_name = $1
         AND d.collected_at >= now() - interval '14 days'
         AND d.collected_at <  now() - interval '7 days') AS calls_previous,
    (SELECT coalesce(count(*), 0)::bigint
       FROM log_events
       WHERE server_name = $1
         AND collected_at >= now() - interval '7 days'
         AND log_level = ANY(ARRAY[5, 7, 8])) AS errors_current,
    (SELECT coalesce(count(*), 0)::bigint
       FROM log_events
       WHERE server_name = $1
         AND collected_at >= now() - interval '14 days'
         AND collected_at <  now() - interval '7 days'
         AND log_level = ANY(ARRAY[5, 7, 8])) AS errors_previous
`

type WeeklyReportSummaryRow struct {
	P99Current     float64
	P99Previous    float64
	CallsCurrent   int64
	CallsPrevious  int64
	ErrorsCurrent  int64
	ErrorsPrevious int64
}

func (q *Queries) WeeklyReportSummary(ctx context.Context, serverName string) (WeeklyReportSummaryRow, error) {
	row := q.db.QueryRow(ctx, weeklyReportSummary, serverName)
	var i WeeklyReportSummaryRow
	err := row.Scan(
		&i.P99Current,
		&i.P99Previous,
		&i.CallsCurrent,
		&i.CallsPrevious,
		&i.ErrorsCurrent,
		&i.ErrorsPrevious,
	)
	return i, err
}

const weeklyReportTopStatements = `-- name: WeeklyReportTopStatements :many
WITH busiest AS (
    SELECT d.statement_id,
           sum(d.total_exec_time)::double precision AS total_ms
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE s.server_name = $1
      AND d.collected_at >= now() - interval '7 days'
    GROUP BY d.statement_id
    ORDER BY total_ms DESC
    LIMIT $2
)
SELECT busiest.statement_id AS id,
       busiest.total_ms,
       coalesce(st.tags, '{}'::jsonb) AS tags
FROM busiest
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(per_key.key, per_key.value) AS tags
    FROM (
        SELECT kv.key, min(kv.value) AS value
        FROM statement_samples qs
        CROSS JOIN LATERAL jsonb_each_text(qs.tags) AS kv(key, value)
        WHERE qs.statement_id = busiest.statement_id
          AND qs.tags IS NOT NULL
          AND kv.key NOT LIKE '%\_id'
          AND qs.collected_at >= now() - interval '7 days'
        GROUP BY kv.key
        HAVING count(DISTINCT kv.value) = 1
    ) per_key
) st ON true
ORDER BY busiest.total_ms DESC
`

type WeeklyReportTopStatementsParams struct {
	ServerName string
	MaxRows    int32
}

type WeeklyReportTopStatementsRow struct {
	ID      int64
	TotalMs float64
	Tags    []byte
}

func (q *Queries) WeeklyReportTopStatements(ctx context.Context, arg WeeklyReportTopStatementsParams) ([]WeeklyReportTopStatementsRow, error) {
	rows, err := q.db.Query(ctx, weeklyReportTopStatements, arg.ServerName, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WeeklyReportTopStatementsRow
	for rows.Next() {
		var i WeeklyReportTopStatementsRow
		if err := rows.Scan(&i.ID, &i.TotalMs, &i.Tags); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
