// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const alertDigestSummary = `-- name: AlertDigestSummary :one
SELECT
    (SELECT coalesce(sum(d.total_exec_time), 0)::double precision
       FROM statement_deltas d JOIN statements s ON s.id = d.statement_id
       WHERE s.server_name = $1
         AND d.collected_at >= now() - interval '7 days') AS exec_ms_current,
    (SELECT coalesce(sum(d.total_exec_time), 0)::double precision
       FROM statement_deltas d JOIN statements s ON s.id = d.statement_id
       WHERE s.server_name = $1
         AND d.collected_at >= now() - interval '14 days'
         AND d.collected_at <  now() - interval '7 days') AS exec_ms_previous,
    (SELECT coalesce(count(*), 0)::bigint
       FROM log_events
       WHERE server_name = $1
         AND collected_at >= now() - interval '7 days'
         AND log_level = ANY(ARRAY[5, 7, 8])) AS errors_current,
    (SELECT coalesce(count(*), 0)::bigint
       FROM log_events
       WHERE server_name = $1
         AND collected_at >= now() - interval '14 days'
         AND collected_at <  now() - interval '7 days'
         AND log_level = ANY(ARRAY[5, 7, 8])) AS errors_previous
`

type AlertDigestSummaryRow struct {
	ExecMsCurrent  float64
	ExecMsPrevious float64
	ErrorsCurrent  int64
	ErrorsPrevious int64
}

func (q *Queries) AlertDigestSummary(ctx context.Context, serverName string) (AlertDigestSummaryRow, error) {
	row := q.db.QueryRow(ctx, alertDigestSummary, serverName)
	var i AlertDigestSummaryRow
	err := row.Scan(
		&i.ExecMsCurrent,
		&i.ExecMsPrevious,
		&i.ErrorsCurrent,
		&i.ErrorsPrevious,
	)
	return i, err
}

const alertDigestTopStatements = `-- name: AlertDigestTopStatements :many
SELECT s.query_full AS query,
       sum(d.total_exec_time)::double precision AS total_exec_time
FROM statement_deltas d
JOIN statements s ON s.id = d.statement_id
WHERE s.server_name = $1
  AND d.collected_at >= now() - interval '7 days'
GROUP BY s.query_full
ORDER BY total_exec_time DESC
LIMIT 5
`

type AlertDigestTopStatementsRow struct {
	Query         string
	TotalExecTime float64
}

func (q *Queries) AlertDigestTopStatements(ctx context.Context, serverName string) ([]AlertDigestTopStatementsRow, error) {
	rows, err := q.db.Query(ctx, alertDigestTopStatements, serverName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertDigestTopStatementsRow
	for rows.Next() {
		var i AlertDigestTopStatementsRow
		if err := rows.Scan(&i.Query, &i.TotalExecTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCollectorTokensForServer = `-- name: CountCollectorTokensForServer :one
SELECT count(*) AS total FROM collector_tokens WHERE server_name = $1
`

func (q *Queries) CountCollectorTokensForServer(ctx context.Context, serverName string) (int64, error) {
	row := q.db.QueryRow(ctx, countCollectorTokensForServer, serverName)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) AS total FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createCollectorToken = `-- name: CreateCollectorToken :one
INSERT INTO collector_tokens (server_name, token_hash)
VALUES ($1, $2)
RETURNING id, server_name, created_at
`

type CreateCollectorTokenParams struct {
	ServerName string
	TokenHash  string
}

type CreateCollectorTokenRow struct {
	ID         int64
	ServerName string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateCollectorToken(ctx context.Context, arg CreateCollectorTokenParams) (CreateCollectorTokenRow, error) {
	row := q.db.QueryRow(ctx, createCollectorToken, arg.ServerName, arg.TokenHash)
	var i CreateCollectorTokenRow
	err := row.Scan(&i.ID, &i.ServerName, &i.CreatedAt)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password_hash, is_super_admin, allowed_servers)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, email, is_super_admin, created_at, allowed_servers
`

type CreateUserParams struct {
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	AllowedServers []string
}

type CreateUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.IsSuperAdmin,
		arg.AllowedServers,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const deleteAlertConfigForServer = `-- name: DeleteAlertConfigForServer :exec
WITH cleared_settings AS (
    DELETE FROM alert_settings WHERE alert_settings.server_name = $1
),
cleared_toggles AS (
    DELETE FROM alert_toggles WHERE alert_toggles.server_name = $1
)
DELETE FROM alert_notifications WHERE alert_notifications.server_name = $1
`

func (q *Queries) DeleteAlertConfigForServer(ctx context.Context, serverName string) error {
	_, err := q.db.Exec(ctx, deleteAlertConfigForServer, serverName)
	return err
}

const deleteCollectorToken = `-- name: DeleteCollectorToken :one
DELETE FROM collector_tokens WHERE id = $1
RETURNING server_name
`

func (q *Queries) DeleteCollectorToken(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRow(ctx, deleteCollectorToken, id)
	var server_name string
	err := row.Scan(&server_name)
	return server_name, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const filterStatementIDsByTags = `-- name: FilterStatementIDsByTags :many
WITH scoped AS (
    SELECT s.id
    FROM statements s
    WHERE ($2::text IS NULL OR s.server_name = $2)
      AND ($3::text IS NULL OR s.database_name = $3)
      AND ($4::text[] IS NULL OR s.server_name = ANY($4::text[]))
),
agreed AS (
    SELECT ss.statement_id, kv.key, min(kv.value) AS value
    FROM statement_samples ss
    JOIN scoped ON scoped.id = ss.statement_id
    CROSS JOIN LATERAL jsonb_each_text(ss.tags) AS kv(key, value)
    WHERE ss.tags IS NOT NULL
      AND kv.key NOT LIKE '%\_id'
      AND ss.collected_at >= $5::timestamptz
      AND ss.collected_at <= $6::timestamptz
      AND kv.key IN (SELECT f ->> 'key' FROM jsonb_array_elements($1::jsonb) AS f)
    GROUP BY ss.statement_id, kv.key
    HAVING count(DISTINCT kv.value) = 1
)
SELECT scoped.id
FROM scoped
WHERE NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements($1::jsonb) AS f
    WHERE NOT CASE f ->> 'op'
        WHEN 'ne' THEN NOT EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
              AND a.value IN (SELECT jsonb_array_elements_text(f -> 'values'))
        )
        WHEN 'exists' THEN EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
        )
        ELSE EXISTS (
            SELECT 1 FROM agreed a
            WHERE a.statement_id = scoped.id
              AND a.key = (f ->> 'key')
              AND a.value IN (SELECT jsonb_array_elements_text(f -> 'values'))
        )
    END
)
`

type FilterStatementIDsByTagsParams struct {
	TagFilters     []byte
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
}

func (q *Queries) FilterStatementIDsByTags(ctx context.Context, arg FilterStatementIDsByTagsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, filterStatementIDsByTags,
		arg.TagFilters,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlertEnabled = `-- name: GetAlertEnabled :one
SELECT enabled FROM alert_toggles WHERE server_name = $1 AND alert_key = $2
`

type GetAlertEnabledParams struct {
	ServerName string
	AlertKey   string
}

func (q *Queries) GetAlertEnabled(ctx context.Context, arg GetAlertEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, getAlertEnabled, arg.ServerName, arg.AlertKey)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const getAlertWebhook = `-- name: GetAlertWebhook :one
SELECT slack_webhook_url FROM alert_settings WHERE server_name = $1
`

func (q *Queries) GetAlertWebhook(ctx context.Context, serverName string) (string, error) {
	row := q.db.QueryRow(ctx, getAlertWebhook, serverName)
	var slack_webhook_url string
	err := row.Scan(&slack_webhook_url)
	return slack_webhook_url, err
}

const getCollectorServerByHash = `-- name: GetCollectorServerByHash :one
SELECT server_name FROM collector_tokens WHERE token_hash = $1
`

func (q *Queries) GetCollectorServerByHash(ctx context.Context, tokenHash string) (string, error) {
	row := q.db.QueryRow(ctx, getCollectorServerByHash, tokenHash)
	var server_name string
	err := row.Scan(&server_name)
	return server_name, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT u.id, u.name, u.email, u.is_super_admin, u.created_at, u.allowed_servers
FROM user_sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash string) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const getStatementDetail = `-- name: GetStatementDetail :one
SELECT
    s.query_full AS query,
    s.server_name,
    s.database_name,
    coalesce(st.tags, '{}'::jsonb) AS tags
FROM statements s
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(per_key.key, per_key.value) AS tags
    FROM (
        SELECT
            kv.key,
            min(kv.value) AS value
        FROM statement_samples qs
        CROSS JOIN LATERAL jsonb_each_text(qs.tags) AS kv(key, value)
        WHERE qs.statement_id = s.id
          AND qs.tags IS NOT NULL
          AND kv.key NOT LIKE '%\_id'
          AND ($1::timestamptz IS NULL OR qs.collected_at >= $1)
          AND ($2::timestamptz IS NULL OR qs.collected_at <= $2)
        GROUP BY kv.key
        HAVING count(DISTINCT kv.value) = 1
    ) per_key
) st ON true
WHERE s.id = $3
  AND ($4::text[] IS NULL OR s.server_name = ANY($4::text[]))
`

type GetStatementDetailParams struct {
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	StatementID    int64
	AllowedServers []string
}

type GetStatementDetailRow struct {
	Query        string
	ServerName   string
	DatabaseName string
	Tags         []byte
}

func (q *Queries) GetStatementDetail(ctx context.Context, arg GetStatementDetailParams) (GetStatementDetailRow, error) {
	row := q.db.QueryRow(ctx, getStatementDetail,
		arg.Since,
		arg.Until,
		arg.StatementID,
		arg.AllowedServers,
	)
	var i GetStatementDetailRow
	err := row.Scan(
		&i.Query,
		&i.ServerName,
		&i.DatabaseName,
		&i.Tags,
	)
	return i, err
}

const getStatementSamplePlan = `-- name: GetStatementSamplePlan :one
SELECT query, parameters, explain_plan_json
FROM statement_samples
WHERE id = $1
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
`

type GetStatementSamplePlanParams struct {
	SampleID       int64
	AllowedServers []string
}

type GetStatementSamplePlanRow struct {
	Query           string
	Parameters      []string
	ExplainPlanJson pgtype.Text
}

func (q *Queries) GetStatementSamplePlan(ctx context.Context, arg GetStatementSamplePlanParams) (GetStatementSamplePlanRow, error) {
	row := q.db.QueryRow(ctx, getStatementSamplePlan, arg.SampleID, arg.AllowedServers)
	var i GetStatementSamplePlanRow
	err := row.Scan(&i.Query, &i.Parameters, &i.ExplainPlanJson)
	return i, err
}

const getStatementSampleText = `-- name: GetStatementSampleText :one
SELECT query, parameters
FROM statement_samples
WHERE id = $1
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
`

type GetStatementSampleTextParams struct {
	SampleID       int64
	AllowedServers []string
}

type GetStatementSampleTextRow struct {
	Query      string
	Parameters []string
}

func (q *Queries) GetStatementSampleText(ctx context.Context, arg GetStatementSampleTextParams) (GetStatementSampleTextRow, error) {
	row := q.db.QueryRow(ctx, getStatementSampleText, arg.SampleID, arg.AllowedServers)
	var i GetStatementSampleTextRow
	err := row.Scan(&i.Query, &i.Parameters)
	return i, err
}

const getStatementText = `-- name: GetStatementText :one
SELECT query_full
FROM statements
WHERE id = $1
  AND ($2::text[] IS NULL
       OR server_name = ANY($2::text[]))
`

type GetStatementTextParams struct {
	ID             int64
	AllowedServers []string
}

func (q *Queries) GetStatementText(ctx context.Context, arg GetStatementTextParams) (string, error) {
	row := q.db.QueryRow(ctx, getStatementText, arg.ID, arg.AllowedServers)
	var query_full string
	err := row.Scan(&query_full)
	return query_full, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, is_super_admin, created_at, allowed_servers
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             int64
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, is_super_admin, created_at, allowed_servers
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int64
	Name           string
	Email          string
	PasswordHash   string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

type InsertLogEventsParams struct {
	ServerName        string
	CollectedAt       pgtype.Timestamptz
	OccurredAt        pgtype.Timestamptz
	LogLevel          int32
	Classification    int32
	Message           pgtype.Text
	Pid               pgtype.Int4
	Username          pgtype.Text
	DatabaseName      pgtype.Text
	ApplicationName   pgtype.Text
	Detail            pgtype.Text
	Hint              pgtype.Text
	Context           pgtype.Text
	Statement         pgtype.Text
	BackendType       pgtype.Text
	StateCode         pgtype.Text
	StatementSampleID pgtype.Int8
}

type InsertStatementDeltasParams struct {
	StatementID   int64
	CollectedAt   pgtype.Timestamptz
	Calls         int64
	Rows          int64
	TotalExecTime float64
	TotalIoTime   float64
}

const listAlertToggles = `-- name: ListAlertToggles :many
SELECT server_name, alert_key, enabled
FROM alert_toggles
WHERE ($1::text[] IS NULL OR server_name = ANY($1::text[]))
`

func (q *Queries) ListAlertToggles(ctx context.Context, allowedServers []string) ([]AlertToggle, error) {
	rows, err := q.db.Query(ctx, listAlertToggles, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertToggle
	for rows.Next() {
		var i AlertToggle
		if err := rows.Scan(&i.ServerName, &i.AlertKey, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertWebhooks = `-- name: ListAlertWebhooks :many
SELECT server_name, slack_webhook_url
FROM alert_settings
WHERE ($1::text[] IS NULL OR server_name = ANY($1::text[]))
`

func (q *Queries) ListAlertWebhooks(ctx context.Context, allowedServers []string) ([]AlertSetting, error) {
	rows, err := q.db.Query(ctx, listAlertWebhooks, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertSetting
	for rows.Next() {
		var i AlertSetting
		if err := rows.Scan(&i.ServerName, &i.SlackWebhookUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedEvents = `-- name: ListBlockedEvents :many
SELECT t.pid AS victim_pid, t.application_name AS victim_app,
       e.lock_wait_start, e.first_seen_at, e.last_seen_at,
       e.lock_mode, e.blocked_by_pid, q.query,
       COALESCE((SELECT bt.application_name FROM transactions bt
         WHERE bt.server_name = t.server_name AND bt.database_name = t.database_name
           AND bt.pid = e.blocked_by_pid
           AND bt.xact_start <= e.last_seen_at AND bt.last_seen_at >= e.first_seen_at
         ORDER BY bt.xact_start DESC LIMIT 1), '')::text AS blocker_app
FROM transaction_events e
JOIN transaction_queries q ON q.id = e.transaction_query_id
JOIN transactions t        ON t.id = q.transaction_id
WHERE e.blocked_by_pid IS NOT NULL
  AND ($1::text   IS NULL OR t.server_name   = $1)
  AND ($2::text IS NULL OR t.database_name = $2)
  AND ($3::text[] IS NULL OR t.server_name = ANY($3::text[]))
  AND e.first_seen_at <= $4
  AND e.last_seen_at  >= $5
ORDER BY e.lock_wait_start, e.id
`

type ListBlockedEventsParams struct {
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	ToTime         pgtype.Timestamptz
	FromTime       pgtype.Timestamptz
}

type ListBlockedEventsRow struct {
	VictimPid     int32
	VictimApp     string
	LockWaitStart pgtype.Timestamptz
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	LockMode      pgtype.Text
	BlockedByPid  pgtype.Int4
	Query         string
	BlockerApp    string
}

func (q *Queries) ListBlockedEvents(ctx context.Context, arg ListBlockedEventsParams) ([]ListBlockedEventsRow, error) {
	rows, err := q.db.Query(ctx, listBlockedEvents,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.ToTime,
		arg.FromTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedEventsRow
	for rows.Next() {
		var i ListBlockedEventsRow
		if err := rows.Scan(
			&i.VictimPid,
			&i.VictimApp,
			&i.LockWaitStart,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.LockMode,
			&i.BlockedByPid,
			&i.Query,
			&i.BlockerApp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectorTokens = `-- name: ListCollectorTokens :many
SELECT id, server_name, created_at FROM collector_tokens ORDER BY created_at, id
`

type ListCollectorTokensRow struct {
	ID         int64
	ServerName string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListCollectorTokens(ctx context.Context) ([]ListCollectorTokensRow, error) {
	rows, err := q.db.Query(ctx, listCollectorTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectorTokensRow
	for rows.Next() {
		var i ListCollectorTokensRow
		if err := rows.Scan(&i.ID, &i.ServerName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingStatementQueryIDs = `-- name: ListExistingStatementQueryIDs :many
SELECT DISTINCT query_id
FROM statements
WHERE server_name = $1
  AND query_id = ANY($2::bigint[])
`

type ListExistingStatementQueryIDsParams struct {
	ServerName string
	QueryIds   []int64
}

func (q *Queries) ListExistingStatementQueryIDs(ctx context.Context, arg ListExistingStatementQueryIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listExistingStatementQueryIDs, arg.ServerName, arg.QueryIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var query_id int64
		if err := rows.Scan(&query_id); err != nil {
			return nil, err
		}
		items = append(items, query_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLogEvents = `-- name: ListLogEvents :many
SELECT id, occurred_at, log_level, classification, message, pid, username,
       database_name, application_name, detail, hint, context, statement,
       backend_type, state_code
FROM log_events
WHERE server_name = $1
  AND ($2::text[] IS NULL OR server_name = ANY($2::text[]))
  AND ($3::timestamptz IS NULL OR occurred_at >= $3)
  AND ($4::timestamptz IS NULL OR occurred_at <= $4)
  AND ($3::timestamptz IS NULL OR collected_at >= $3)
  AND ($5::int[] IS NULL OR log_level = ANY($5::int[]))
  AND ($6::int[] IS NULL OR classification = ANY($6::int[]))
  AND ($7::text IS NULL
       OR message ILIKE '%' || $7::text || '%'
       OR detail ILIKE '%' || $7::text || '%'
       OR statement ILIKE '%' || $7::text || '%'
       OR pid::text = $7::text)
ORDER BY occurred_at DESC NULLS LAST, id DESC
LIMIT $8
`

type ListLogEventsParams struct {
	ServerName      string
	AllowedServers  []string
	Since           pgtype.Timestamptz
	Until           pgtype.Timestamptz
	Levels          []int32
	Classifications []int32
	Search          pgtype.Text
	RowLimit        int32
}

type ListLogEventsRow struct {
	ID              int64
	OccurredAt      pgtype.Timestamptz
	LogLevel        int32
	Classification  int32
	Message         pgtype.Text
	Pid             pgtype.Int4
	Username        pgtype.Text
	DatabaseName    pgtype.Text
	ApplicationName pgtype.Text
	Detail          pgtype.Text
	Hint            pgtype.Text
	Context         pgtype.Text
	Statement       pgtype.Text
	BackendType     pgtype.Text
	StateCode       pgtype.Text
}

func (q *Queries) ListLogEvents(ctx context.Context, arg ListLogEventsParams) ([]ListLogEventsRow, error) {
	rows, err := q.db.Query(ctx, listLogEvents,
		arg.ServerName,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
		arg.Levels,
		arg.Classifications,
		arg.Search,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLogEventsRow
	for rows.Next() {
		var i ListLogEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.LogLevel,
			&i.Classification,
			&i.Message,
			&i.Pid,
			&i.Username,
			&i.DatabaseName,
			&i.ApplicationName,
			&i.Detail,
			&i.Hint,
			&i.Context,
			&i.Statement,
			&i.BackendType,
			&i.StateCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitoredServers = `-- name: ListMonitoredServers :many
SELECT server_name, collected_at, databases
FROM collector_health
WHERE collected_at >= now() - interval '24 hours'
  AND ($1::text[] IS NULL OR server_name = ANY($1::text[]))
ORDER BY server_name
`

func (q *Queries) ListMonitoredServers(ctx context.Context, allowedServers []string) ([]CollectorHealth, error) {
	rows, err := q.db.Query(ctx, listMonitoredServers, allowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectorHealth
	for rows.Next() {
		var i CollectorHealth
		if err := rows.Scan(&i.ServerName, &i.CollectedAt, &i.Databases); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersWithDigestEnabled = `-- name: ListServersWithDigestEnabled :many
SELECT s.server_name
FROM alert_settings s
LEFT JOIN alert_toggles t
  ON t.server_name = s.server_name AND t.alert_key = $1
WHERE s.slack_webhook_url <> ''
  AND coalesce(t.enabled, true)
ORDER BY s.server_name
`

func (q *Queries) ListServersWithDigestEnabled(ctx context.Context, alertKey string) ([]string, error) {
	rows, err := q.db.Query(ctx, listServersWithDigestEnabled, alertKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_name string
		if err := rows.Scan(&server_name); err != nil {
			return nil, err
		}
		items = append(items, server_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleServers = `-- name: ListStaleServers :many
SELECT server_name
FROM collector_health
WHERE collected_at < now() - $1::interval
  AND collected_at >= now() - interval '24 hours'
ORDER BY server_name
`

func (q *Queries) ListStaleServers(ctx context.Context, staleAfter pgtype.Interval) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleServers, staleAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_name string
		if err := rows.Scan(&server_name); err != nil {
			return nil, err
		}
		items = append(items, server_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementSamples = `-- name: ListStatementSamples :many
SELECT id, occurred_at, query, duration_ms, parameters, explain_plan_json, tags
FROM statement_samples s
WHERE s.statement_id = $1
  AND ($2::text[] IS NULL OR s.server_name = ANY($2::text[]))
  AND ($3::timestamptz IS NULL OR s.collected_at >= $3)
  AND ($4::timestamptz IS NULL OR s.collected_at <= $4)
  AND NOT (
      -- Drop this log_min_duration row when auto_explain logged the same run.
      s.explain_plan_json IS NULL
      AND EXISTS (
          SELECT 1
          FROM statement_samples e
          WHERE e.statement_id = s.statement_id
            AND e.explain_plan_json IS NOT NULL
            AND e.query = s.query
            AND e.parameters IS NOT DISTINCT FROM s.parameters
            AND e.occurred_at BETWEEN s.occurred_at - interval '1 second'
                                  AND s.occurred_at + interval '1 second'
            AND abs(e.duration_ms - s.duration_ms) <= 1
            AND ($3::timestamptz IS NULL OR e.collected_at >= $3)
            AND ($4::timestamptz IS NULL OR e.collected_at <= $4)
      )
  )
ORDER BY s.occurred_at DESC, s.id DESC
LIMIT $6
OFFSET $5
`

type ListStatementSamplesParams struct {
	StatementID    pgtype.Int8
	AllowedServers []string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	OffsetRows     int32
	RowLimit       int32
}

type ListStatementSamplesRow struct {
	ID              int64
	OccurredAt      pgtype.Timestamptz
	Query           string
	DurationMs      float64
	Parameters      []string
	ExplainPlanJson pgtype.Text
	Tags            []byte
}

func (q *Queries) ListStatementSamples(ctx context.Context, arg ListStatementSamplesParams) ([]ListStatementSamplesRow, error) {
	rows, err := q.db.Query(ctx, listStatementSamples,
		arg.StatementID,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
		arg.OffsetRows,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementSamplesRow
	for rows.Next() {
		var i ListStatementSamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.Query,
			&i.DurationMs,
			&i.Parameters,
			&i.ExplainPlanJson,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementStats = `-- name: ListStatementStats :many
WITH per_all AS (
    SELECT
        s.id,
        s.query_short AS preview,
        s.user_name,
        (($5::text IS NULL
          OR s.query_full ILIKE '%' || $5::text || '%')
         AND ($6::bigint[] IS NULL
              OR s.id = ANY($6::bigint[]))
         AND s.query_kind = ANY($7::int[])) AS matched,
        sum(d.calls)::bigint                     AS calls,
        sum(d.rows)::bigint                      AS rows,
        sum(d.total_exec_time)::double precision AS total_exec_time,
        sum(d.total_io_time)::double precision   AS total_io_time
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE ($8::text IS NULL OR s.server_name = $8)
      AND ($9::text IS NULL OR s.database_name = $9)
      AND ($10::text[] IS NULL OR s.server_name = ANY($10::text[]))
      AND ($11::timestamptz IS NULL OR d.collected_at >= $11)
      AND ($12::timestamptz IS NULL OR d.collected_at <= $12)
    GROUP BY s.id, 4
),
totals AS (
    SELECT
        sum(total_exec_time)::double precision AS total_exec_time,
        sum(total_io_time)::double precision   AS total_io_time
    FROM per_all
),
per_statement AS (
    SELECT id, preview, user_name, calls, rows, total_exec_time, total_io_time
    FROM per_all
    WHERE matched
),
statement_tags AS (
    SELECT statement_id, jsonb_object_agg(key, value) AS tags
    FROM (
        SELECT dt.statement_id, kv.key, min(kv.value) AS value
        FROM (
            SELECT DISTINCT qs.statement_id, qs.tags
            FROM statement_samples qs
            WHERE qs.tags IS NOT NULL
              AND qs.statement_id IN (SELECT id FROM per_statement)
              AND ($11::timestamptz IS NULL OR qs.collected_at >= $11)
              AND ($12::timestamptz IS NULL OR qs.collected_at <= $12)
        ) dt
        CROSS JOIN LATERAL jsonb_each_text(dt.tags) AS kv(key, value)
        WHERE kv.key NOT LIKE '%\_id'
        GROUP BY dt.statement_id, kv.key
        HAVING min(kv.value) = max(kv.value)
    ) per_key
    GROUP BY statement_id
)
SELECT
    ps.id,
    ps.preview,
    ps.user_name,
    ps.calls,
    ps.rows,
    ps.total_exec_time,
    (coalesce(ps.total_exec_time / NULLIF((SELECT total_exec_time FROM totals), 0), 0) * 100)::double precision AS pct_of_total,
    (coalesce(ps.total_io_time / NULLIF((SELECT total_io_time FROM totals), 0), 0) * 100)::double precision AS pct_io,
    coalesce(st.tags, '{}'::jsonb) AS tags
FROM per_statement ps
LEFT JOIN statement_tags st ON st.statement_id = ps.id
ORDER BY
    CASE WHEN $1::text = 'query' AND $2::bool THEN ps.preview END DESC,
    CASE WHEN $1::text = 'query' AND NOT $2::bool THEN ps.preview END ASC,
    CASE WHEN $1::text = 'user' AND $2::bool THEN ps.user_name END DESC,
    CASE WHEN $1::text = 'user' AND NOT $2::bool THEN ps.user_name END ASC,
    CASE WHEN $2::bool THEN
        CASE $1::text
            WHEN 'avg' THEN ps.total_exec_time / NULLIF(ps.calls, 0)
            WHEN 'calls' THEN ps.calls::double precision
            WHEN 'rows_per_call' THEN ps.rows::double precision / NULLIF(ps.calls, 0)
            WHEN 'pct_io' THEN ps.total_io_time
            ELSE ps.total_exec_time
        END
    END DESC,
    CASE WHEN NOT $2::bool THEN
        CASE $1::text
            WHEN 'avg' THEN ps.total_exec_time / NULLIF(ps.calls, 0)
            WHEN 'calls' THEN ps.calls::double precision
            WHEN 'rows_per_call' THEN ps.rows::double precision / NULLIF(ps.calls, 0)
            WHEN 'pct_io' THEN ps.total_io_time
            ELSE ps.total_exec_time
        END
    END ASC,
    ps.id DESC
LIMIT $4
OFFSET $3
`

type ListStatementStatsParams struct {
	SortKey        string
	SortDesc       bool
	OffsetRows     int32
	RowLimit       int32
	TextFilter     pgtype.Text
	StatementIds   []int64
	Kinds          []int32
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
}

type ListStatementStatsRow struct {
	ID            int64
	Preview       string
	UserName      string
	Calls         int64
	Rows          int64
	TotalExecTime float64
	PctOfTotal    float64
	PctIo         float64
	Tags          []byte
}

func (q *Queries) ListStatementStats(ctx context.Context, arg ListStatementStatsParams) ([]ListStatementStatsRow, error) {
	rows, err := q.db.Query(ctx, listStatementStats,
		arg.SortKey,
		arg.SortDesc,
		arg.OffsetRows,
		arg.RowLimit,
		arg.TextFilter,
		arg.StatementIds,
		arg.Kinds,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.Since,
		arg.Until,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementStatsRow
	for rows.Next() {
		var i ListStatementStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Preview,
			&i.UserName,
			&i.Calls,
			&i.Rows,
			&i.TotalExecTime,
			&i.PctOfTotal,
			&i.PctIo,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementsMissingText = `-- name: ListStatementsMissingText :many
SELECT user_name, database_name, query_id
FROM statements
WHERE id = ANY($1::bigint[])
  AND query_full = ''
`

type ListStatementsMissingTextRow struct {
	UserName     string
	DatabaseName string
	QueryID      int64
}

func (q *Queries) ListStatementsMissingText(ctx context.Context, ids []int64) ([]ListStatementsMissingTextRow, error) {
	rows, err := q.db.Query(ctx, listStatementsMissingText, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsMissingTextRow
	for rows.Next() {
		var i ListStatementsMissingTextRow
		if err := rows.Scan(&i.UserName, &i.DatabaseName, &i.QueryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagKeys = `-- name: ListTagKeys :many
WITH agreed AS (
    SELECT ss.statement_id, kv.key, min(kv.value) AS value
    FROM statement_samples ss
    JOIN statements s ON s.id = ss.statement_id
    CROSS JOIN LATERAL jsonb_each_text(ss.tags) AS kv(key, value)
    WHERE ss.tags IS NOT NULL
      AND ss.statement_id IS NOT NULL
      AND kv.key NOT LIKE '%\_id'
      AND ss.collected_at >= $1::timestamptz
      AND ss.collected_at <= $2::timestamptz
      AND ($3::text IS NULL OR ss.server_name = $3)
      AND ($4::text IS NULL OR s.database_name = $4)
      AND ($5::text[] IS NULL OR ss.server_name = ANY($5::text[]))
    GROUP BY ss.statement_id, kv.key
    HAVING count(DISTINCT kv.value) = 1
)
SELECT
    key::text                     AS key,
    count(DISTINCT value)::bigint AS value_count
FROM agreed
GROUP BY key
ORDER BY count(DISTINCT statement_id) DESC, key
`

type ListTagKeysParams struct {
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type ListTagKeysRow struct {
	Key        string
	ValueCount int64
}

func (q *Queries) ListTagKeys(ctx context.Context, arg ListTagKeysParams) ([]ListTagKeysRow, error) {
	rows, err := q.db.Query(ctx, listTagKeys,
		arg.Since,
		arg.Until,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagKeysRow
	for rows.Next() {
		var i ListTagKeysRow
		if err := rows.Scan(&i.Key, &i.ValueCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagValues = `-- name: ListTagValues :many
WITH agreed AS (
    SELECT
        ss.statement_id,
        min(ss.tags ->> $1::text) AS value
    FROM statement_samples ss
    JOIN statements s ON s.id = ss.statement_id
    WHERE ss.tags ? $1::text
      AND $1::text NOT LIKE '%\_id'
      AND ss.statement_id IS NOT NULL
      AND ss.collected_at >= $2::timestamptz
      AND ss.collected_at <= $3::timestamptz
      AND ($4::text IS NULL OR ss.server_name = $4)
      AND ($5::text IS NULL OR s.database_name = $5)
      AND ($6::text[] IS NULL OR ss.server_name = ANY($6::text[]))
    GROUP BY ss.statement_id
    HAVING count(DISTINCT ss.tags ->> $1::text) = 1
)
SELECT
    value::text                          AS value,
    count(DISTINCT statement_id)::bigint AS statement_count
FROM agreed
GROUP BY value
ORDER BY statement_count DESC, value
`

type ListTagValuesParams struct {
	TagKey         string
	Since          pgtype.Timestamptz
	Until          pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type ListTagValuesRow struct {
	Value          string
	StatementCount int64
}

func (q *Queries) ListTagValues(ctx context.Context, arg ListTagValuesParams) ([]ListTagValuesRow, error) {
	rows, err := q.db.Query(ctx, listTagValues,
		arg.TagKey,
		arg.Since,
		arg.Until,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagValuesRow
	for rows.Next() {
		var i ListTagValuesRow
		if err := rows.Scan(&i.Value, &i.StatementCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionEvents = `-- name: ListTransactionEvents :many
SELECT q.transaction_id, e.state, e.wait_event_type, e.wait_event, e.lock_mode,
       q.query, q.query_tags, e.first_seen_at, e.last_seen_at
FROM transaction_events e
JOIN transaction_queries q ON q.id = e.transaction_query_id
JOIN transactions t ON t.id = q.transaction_id
WHERE q.transaction_id = ANY($1::bigint[])
  AND ($2::text[] IS NULL OR t.server_name = ANY($2::text[]))
ORDER BY q.transaction_id, e.first_seen_at, e.id
`

type ListTransactionEventsParams struct {
	TransactionIds []int64
	AllowedServers []string
}

type ListTransactionEventsRow struct {
	TransactionID int64
	State         string
	WaitEventType pgtype.Text
	WaitEvent     pgtype.Text
	LockMode      pgtype.Text
	Query         string
	QueryTags     []byte
	FirstSeenAt   pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
}

func (q *Queries) ListTransactionEvents(ctx context.Context, arg ListTransactionEventsParams) ([]ListTransactionEventsRow, error) {
	rows, err := q.db.Query(ctx, listTransactionEvents, arg.TransactionIds, arg.AllowedServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionEventsRow
	for rows.Next() {
		var i ListTransactionEventsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.State,
			&i.WaitEventType,
			&i.WaitEvent,
			&i.LockMode,
			&i.Query,
			&i.QueryTags,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, pid, application_name, xact_start, last_seen_at
FROM transactions
WHERE ($1::text   IS NULL OR server_name   = $1)
  AND ($2::text IS NULL OR database_name = $2)
  AND ($3::text[] IS NULL OR server_name = ANY($3::text[]))
  AND xact_start   <= $4
  AND last_seen_at >= $5
ORDER BY (last_seen_at - xact_start) DESC, id DESC
LIMIT $6
`

type ListTransactionsParams struct {
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
	ToTime         pgtype.Timestamptz
	FromTime       pgtype.Timestamptz
	RowLimit       int32
}

type ListTransactionsRow struct {
	ID              int64
	Pid             int32
	ApplicationName string
	XactStart       pgtype.Timestamptz
	LastSeenAt      pgtype.Timestamptz
}

// Transactions overlapping [from, to], longest first.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
		arg.ToTime,
		arg.FromTime,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.ApplicationName,
			&i.XactStart,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, is_super_admin, created_at, allowed_servers
FROM users
ORDER BY created_at, id
`

type ListUsersRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsSuperAdmin,
			&i.CreatedAt,
			&i.AllowedServers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logEventHistogram = `-- name: LogEventHistogram :many
SELECT date_bin($1::interval, occurred_at, $2::timestamptz)::timestamptz AS bucket_start,
       log_level,
       count(*)::bigint AS n
FROM log_events
WHERE server_name = $3
  AND occurred_at IS NOT NULL
  AND occurred_at >= $2::timestamptz
  AND occurred_at <= $4::timestamptz
  AND collected_at >= $2::timestamptz
  AND ($5::text[] IS NULL OR server_name = ANY($5::text[]))
  AND ($6::int[] IS NULL OR classification = ANY($6::int[]))
  AND ($7::text IS NULL
       OR message ILIKE '%' || $7::text || '%'
       OR detail ILIKE '%' || $7::text || '%'
       OR statement ILIKE '%' || $7::text || '%'
       OR pid::text = $7::text)
GROUP BY 1, 2
ORDER BY 1, 2
`

type LogEventHistogramParams struct {
	Bucket          pgtype.Interval
	Since           pgtype.Timestamptz
	ServerName      string
	Until           pgtype.Timestamptz
	AllowedServers  []string
	Classifications []int32
	Search          pgtype.Text
}

type LogEventHistogramRow struct {
	BucketStart pgtype.Timestamptz
	LogLevel    int32
	N           int64
}

func (q *Queries) LogEventHistogram(ctx context.Context, arg LogEventHistogramParams) ([]LogEventHistogramRow, error) {
	rows, err := q.db.Query(ctx, logEventHistogram,
		arg.Bucket,
		arg.Since,
		arg.ServerName,
		arg.Until,
		arg.AllowedServers,
		arg.Classifications,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LogEventHistogramRow
	for rows.Next() {
		var i LogEventHistogramRow
		if err := rows.Scan(&i.BucketStart, &i.LogLevel, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeServerFromUsers = `-- name: RemoveServerFromUsers :exec
UPDATE users SET allowed_servers = array_remove(allowed_servers, $1::text)
`

func (q *Queries) RemoveServerFromUsers(ctx context.Context, serverName string) error {
	_, err := q.db.Exec(ctx, removeServerFromUsers, serverName)
	return err
}

const rollupStatementLatencyBins = `-- name: RollupStatementLatencyBins :exec
WITH cleared AS (
    DELETE FROM statement_latency_bins
    WHERE minute_start >= $1::timestamptz
      AND minute_start <  $2::timestamptz
    RETURNING 1
),
binned AS (
    SELECT date_trunc('minute', d.collected_at - interval '1 microsecond') AS minute_start,
           s.server_name,
           s.database_name,
           floor(ln(greatest(d.total_exec_time / d.calls, 0.001)) / ln(1.01))::smallint AS bin,
           sum(d.calls)::integer AS weight
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $1::timestamptz
      AND d.collected_at <= $2::timestamptz
      AND d.calls > 0
      AND s.query_kind <> $3::int
      AND (SELECT count(*) FROM cleared) >= 0
    GROUP BY 1, 2, 3, 4
)
INSERT INTO statement_latency_bins (minute_start, server_name, database_name, bins, weights)
SELECT minute_start, server_name, database_name,
       array_agg(bin ORDER BY bin), array_agg(weight ORDER BY bin)
FROM binned
GROUP BY minute_start, server_name, database_name
`

type RollupStatementLatencyBinsParams struct {
	RangeStart  pgtype.Timestamptz
	RangeEnd    pgtype.Timestamptz
	UtilityKind int32
}

// Turns raw deltas from a time range into one summed latency histogram per minute.
func (q *Queries) RollupStatementLatencyBins(ctx context.Context, arg RollupStatementLatencyBinsParams) error {
	_, err := q.db.Exec(ctx, rollupStatementLatencyBins, arg.RangeStart, arg.RangeEnd, arg.UtilityKind)
	return err
}

const statementLatencyBins = `-- name: StatementLatencyBins :many
SELECT minute_start, bins, weights
FROM statement_latency_bins
WHERE minute_start >= $1::timestamptz
  AND minute_start <  $2::timestamptz
  AND ($3::text IS NULL OR server_name = $3)
  AND ($4::text IS NULL OR database_name = $4)
  AND ($5::text[] IS NULL
       OR server_name = ANY($5::text[]))
`

type StatementLatencyBinsParams struct {
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type StatementLatencyBinsRow struct {
	MinuteStart pgtype.Timestamptz
	Bins        []int16
	Weights     []int32
}

// Fetches those ready-made histograms for the chart's time window.
func (q *Queries) StatementLatencyBins(ctx context.Context, arg StatementLatencyBinsParams) ([]StatementLatencyBinsRow, error) {
	rows, err := q.db.Query(ctx, statementLatencyBins,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementLatencyBinsRow
	for rows.Next() {
		var i StatementLatencyBinsRow
		if err := rows.Scan(&i.MinuteStart, &i.Bins, &i.Weights); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementLatencyRollupResume = `-- name: StatementLatencyRollupResume :one
SELECT coalesce(
    (SELECT max(minute_start) FROM statement_latency_bins),
    (SELECT min(collected_at) FROM statement_deltas),
    now()
)::timestamptz AS resume_from
`

// Where the rollup job picks up.
func (q *Queries) StatementLatencyRollupResume(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, statementLatencyRollupResume)
	var resume_from pgtype.Timestamptz
	err := row.Scan(&resume_from)
	return resume_from, err
}

const statementLatencyTailBins = `-- name: StatementLatencyTailBins :many
WITH binned AS (
    SELECT date_trunc('minute', d.collected_at - interval '1 microsecond') AS minute_start,
           floor(ln(greatest(d.total_exec_time / d.calls, 0.001)) / ln(1.01))::smallint AS bin,
           sum(d.calls)::integer AS weight
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $1::timestamptz + interval '1 minute'
      AND d.collected_at <= $2::timestamptz
      AND d.calls > 0
      AND s.query_kind <> $3::int
      AND ($4::text IS NULL OR s.server_name = $4)
      AND ($5::text IS NULL OR s.database_name = $5)
      AND ($6::text[] IS NULL
           OR s.server_name = ANY($6::text[]))
    GROUP BY 1, 2
)
SELECT minute_start::timestamptz AS minute_start,
       array_agg(bin ORDER BY bin)::smallint[]   AS bins,
       array_agg(weight ORDER BY bin)::integer[] AS weights
FROM binned
GROUP BY minute_start
`

type StatementLatencyTailBinsParams struct {
	TailStart      pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	UtilityKind    int32
	ServerName     pgtype.Text
	DatabaseName   pgtype.Text
	AllowedServers []string
}

type StatementLatencyTailBinsRow struct {
	MinuteStart pgtype.Timestamptz
	Bins        []int16
	Weights     []int32
}

// Fills the last minute or two the writer hasn't reached yet, straight from raw deltas, so fresh data still shows up.
func (q *Queries) StatementLatencyTailBins(ctx context.Context, arg StatementLatencyTailBinsParams) ([]StatementLatencyTailBinsRow, error) {
	rows, err := q.db.Query(ctx, statementLatencyTailBins,
		arg.TailStart,
		arg.RangeEnd,
		arg.UtilityKind,
		arg.ServerName,
		arg.DatabaseName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementLatencyTailBinsRow
	for rows.Next() {
		var i StatementLatencyTailBinsRow
		if err := rows.Scan(&i.MinuteStart, &i.Bins, &i.Weights); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statementMetricSeries = `-- name: StatementMetricSeries :many
WITH scoped AS (
    SELECT
        date_bin($1::interval,
                 d.collected_at - interval '1 microsecond',
                 $2::timestamptz) + $1::interval AS bucket_end,
        d.total_exec_time,
        d.total_io_time,
        d.calls,
        (($3::text IS NULL OR s.database_name = $3)
         AND ($4::bigint IS NULL OR d.statement_id = $4)
         AND ($5::text IS NULL
              OR s.query_full ILIKE '%' || $5::text || '%')
         AND ($6::bigint[] IS NULL
              OR d.statement_id = ANY($6::bigint[]))) AS matched
    FROM statement_deltas d
    JOIN statements s ON s.id = d.statement_id
    WHERE d.collected_at >  $7::timestamptz
      AND d.collected_at <= $8::timestamptz
      AND ($9::text IS NULL OR s.server_name = $9)
      AND ($10::text[] IS NULL
           OR s.server_name = ANY($10::text[]))
)
SELECT
    bucket_end::timestamptz AS bucket_end,
    coalesce(sum(total_exec_time) FILTER (WHERE matched), 0)::double precision AS total_exec_time,
    coalesce(sum(total_io_time) FILTER (WHERE matched), 0)::double precision   AS total_io_time,
    coalesce(sum(calls) FILTER (WHERE matched), 0)::bigint                     AS calls
FROM scoped
GROUP BY bucket_end
ORDER BY bucket_end
`

type StatementMetricSeriesParams struct {
	Bucket         pgtype.Interval
	Anchor         pgtype.Timestamptz
	DatabaseName   pgtype.Text
	StatementID    pgtype.Int8
	TextFilter     pgtype.Text
	StatementIds   []int64
	RangeStart     pgtype.Timestamptz
	RangeEnd       pgtype.Timestamptz
	ServerName     pgtype.Text
	AllowedServers []string
}

type StatementMetricSeriesRow struct {
	BucketEnd     pgtype.Timestamptz
	TotalExecTime float64
	TotalIoTime   float64
	Calls         int64
}

func (q *Queries) StatementMetricSeries(ctx context.Context, arg StatementMetricSeriesParams) ([]StatementMetricSeriesRow, error) {
	rows, err := q.db.Query(ctx, statementMetricSeries,
		arg.Bucket,
		arg.Anchor,
		arg.DatabaseName,
		arg.StatementID,
		arg.TextFilter,
		arg.StatementIds,
		arg.RangeStart,
		arg.RangeEnd,
		arg.ServerName,
		arg.AllowedServers,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatementMetricSeriesRow
	for rows.Next() {
		var i StatementMetricSeriesRow
		if err := rows.Scan(
			&i.BucketEnd,
			&i.TotalExecTime,
			&i.TotalIoTime,
			&i.Calls,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tryClaimAlertNotification = `-- name: TryClaimAlertNotification :one
INSERT INTO alert_notifications (server_name, alert_key, last_fired_at)
VALUES ($1, $2, now())
ON CONFLICT (server_name, alert_key)
DO UPDATE SET last_fired_at = now()
WHERE alert_notifications.last_fired_at < now() - $3::interval
RETURNING last_fired_at
`

type TryClaimAlertNotificationParams struct {
	ServerName string
	AlertKey   string
	Cooldown   pgtype.Interval
}

func (q *Queries) TryClaimAlertNotification(ctx context.Context, arg TryClaimAlertNotificationParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, tryClaimAlertNotification, arg.ServerName, arg.AlertKey, arg.Cooldown)
	var last_fired_at pgtype.Timestamptz
	err := row.Scan(&last_fired_at)
	return last_fired_at, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1,
    email = $2,
    password_hash = coalesce($3::text, password_hash),
    allowed_servers = $4
WHERE id = $5
RETURNING id, name, email, is_super_admin, created_at, allowed_servers
`

type UpdateUserParams struct {
	Name           string
	Email          string
	PasswordHash   pgtype.Text
	AllowedServers []string
	ID             int64
}

type UpdateUserRow struct {
	ID             int64
	Name           string
	Email          string
	IsSuperAdmin   bool
	CreatedAt      pgtype.Timestamptz
	AllowedServers []string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.AllowedServers,
		arg.ID,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsSuperAdmin,
		&i.CreatedAt,
		&i.AllowedServers,
	)
	return i, err
}

const upsertAlertWebhook = `-- name: UpsertAlertWebhook :exec
INSERT INTO alert_settings (server_name, slack_webhook_url)
VALUES ($1, $2)
ON CONFLICT (server_name) DO UPDATE SET slack_webhook_url = EXCLUDED.slack_webhook_url
`

type UpsertAlertWebhookParams struct {
	ServerName      string
	SlackWebhookUrl string
}

func (q *Queries) UpsertAlertWebhook(ctx context.Context, arg UpsertAlertWebhookParams) error {
	_, err := q.db.Exec(ctx, upsertAlertWebhook, arg.ServerName, arg.SlackWebhookUrl)
	return err
}

const upsertCollectorHealth = `-- name: UpsertCollectorHealth :exec
INSERT INTO collector_health (server_name, collected_at, databases)
VALUES ($1, $2, $3)
ON CONFLICT (server_name) DO UPDATE
SET collected_at = EXCLUDED.collected_at,
    databases = EXCLUDED.databases
`

type UpsertCollectorHealthParams struct {
	ServerName  string
	CollectedAt pgtype.Timestamptz
	Databases   []string
}

func (q *Queries) UpsertCollectorHealth(ctx context.Context, arg UpsertCollectorHealthParams) error {
	_, err := q.db.Exec(ctx, upsertCollectorHealth, arg.ServerName, arg.CollectedAt, arg.Databases)
	return err
}
